import {test,expect} from '@playwright/test';
test.use({trace:'retain-on-failure',screenshot:'only-on-failure'});
const composer=page=>page.getByLabel('消息',{exact:true});
async function sidebar(page){if(!await page.locator('#sidebar').count())await page.getByRole('button',{name:'切换侧栏'}).click()}
async function create(page,canary){
 await sidebar(page);const made=page.waitForResponse(r=>r.url().endsWith('/v1/conversations')&&r.request().method()==='POST');await page.getByRole('button',{name:'＋ 新对话',exact:true}).click();const id=(await(await made).json()).id;await expect(composer(page)).toBeFocused();
 await composer(page).fill('报告[岚]：'+canary);await page.getByRole('button',{name:'发送',exact:true}).click();await expect(composer(page)).toHaveValue('');await expect(page.getByRole('button',{name:'停止',exact:true})).toHaveCount(0);await expect(page.locator('article')).toContainText(canary);return {id,run:await page.locator('article').getAttribute('data-run')};
}
async function select(page,id){await sidebar(page);await page.locator(`[data-conversation="${id}"]`).click()}
async function enter(page){await page.goto('/');await expect(composer(page)).toBeVisible()}
const frames=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));

test('a hanging selected-history read times out without losing newer draft text or enabling writes',async({page},info)=>{
 await enter(page);const a=await create(page,'HISTORY_TIMEOUT_ORIGINAL_A');await page.getByLabel('更多消息操作').click();await page.getByRole('button',{name:'编辑为新消息',exact:true}).click();await composer(page).fill('A_SAVED_DRAFT');await create(page,'HISTORY_TIMEOUT_ORIGINAL_B');let started,release;const waiting=new Promise(resolve=>started=resolve),gate=new Promise(resolve=>release=resolve);let gets=0,posts=0,aborted=0;
 page.on('request',r=>{if(r.url().endsWith(`/v1/conversations/${a.id}`)&&r.method()==='GET')gets++;if(r.method()==='POST')posts++});page.on('requestfailed',r=>{if(r.url().endsWith(`/v1/conversations/${a.id}`))aborted++});
 await page.route(`**/v1/conversations/${a.id}`,async route=>{const response=await route.fetch();started();await gate;await route.fulfill({response}).catch(()=>{})});
 try{await select(page,a.id);await waiting;await expect(composer(page)).toHaveValue('A_SAVED_DRAFT');await composer(page).fill('NEWER_DRAFT_DURING_HISTORY_READ');await expect(page.getByRole('button',{name:'重新读取这段对话',exact:true})).toBeVisible({timeout:17000});await expect(page.locator('#send')).toBeDisabled();await expect(composer(page)).toHaveValue('NEWER_DRAFT_DURING_HISTORY_READ');expect(gets).toBe(1);expect(posts).toBe(0);expect(aborted).toBe(1)}finally{await page.screenshot({path:info.outputPath('history-read-timeout.png'),fullPage:true});release()}
 await page.unroute(`**/v1/conversations/${a.id}`);await page.getByRole('button',{name:'重新读取这段对话',exact:true}).click();await expect(page.locator('article')).toContainText('HISTORY_TIMEOUT_ORIGINAL_A');await expect(page.locator('#send')).toBeEnabled();await expect(composer(page)).toHaveValue('NEWER_DRAFT_DURING_HISTORY_READ');expect(gets).toBe(2);expect(posts).toBe(0);
});

test('a failed search-result history read stays in search and retries explicitly before exact-run focus',async({page},info)=>{
 await enter(page);const a=await create(page,'HISTORY_SEARCH_FAILED_TARGET');await composer(page).fill('SEARCH_TARGET_DRAFT');await create(page,'HISTORY_SEARCH_OTHER');let gets=0,posts=0;page.on('request',r=>{if(r.url().endsWith(`/v1/conversations/${a.id}`)&&r.method()==='GET')gets++;if(r.method()==='POST')posts++});
 await page.route(`**/v1/conversations/${a.id}`,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Original selected-history failure'})}));
 await page.getByRole('button',{name:'搜索对话',exact:true}).click();await page.getByLabel('搜索历史').fill('HISTORY_SEARCH_FAILED_TARGET');const hit=page.locator('.search-hit').filter({hasText:'HISTORY_SEARCH_FAILED_TARGET'}).getByRole('button').first();await hit.click();const dialog=page.getByRole('dialog',{name:'搜索对话'});
 try{await expect(dialog).toBeVisible();await expect(dialog.getByRole('alert')).toContainText('暂时无法打开这条结果');expect(gets).toBe(1);expect(posts).toBe(0)}finally{await page.screenshot({path:info.outputPath('history-search-failure.png'),fullPage:true})}
 await page.unroute(`**/v1/conversations/${a.id}`);await hit.click();await expect(dialog).toHaveCount(0);await expect(page.locator(`[data-run="${a.run}"]`)).toBeFocused();await expect(composer(page)).toHaveValue('SEARCH_TARGET_DRAFT');expect(gets).toBe(2);expect(posts).toBe(0);
});

test('a stale failed history read cannot replace a newer A to B to A visit or its draft',async({page})=>{
 await enter(page);const a=await create(page,'HISTORY_STALE_ORIGINAL_A');await composer(page).fill('STALE_A_SAVED_DRAFT');const b=await create(page,'HISTORY_STALE_ORIGINAL_B');let first=true,started,release;const waiting=new Promise(resolve=>started=resolve),gate=new Promise(resolve=>release=resolve);
 await page.route(`**/v1/conversations/${a.id}`,async route=>{if(!first){await route.continue();return}first=false;started();await gate;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Original stale history failure'})}).catch(()=>{})});
 try{await select(page,a.id);await waiting;await select(page,b.id);await expect(page.locator('article')).toContainText('HISTORY_STALE_ORIGINAL_B');await select(page,a.id);await expect(page.locator('article')).toContainText('HISTORY_STALE_ORIGINAL_A');await expect(composer(page)).toHaveValue('STALE_A_SAVED_DRAFT');release();await frames(page);await expect(page.getByRole('alert')).toHaveCount(0);await expect(composer(page)).toHaveValue('STALE_A_SAVED_DRAFT');await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',a.id)}finally{release()}
});

test('phone selected-history failure is recoverable and never masquerades as an empty new conversation',async({page},info)=>{
 await page.setViewportSize({width:390,height:844});await enter(page);const a=await create(page,'HISTORY_PHONE_RETRY_TARGET');await composer(page).fill('PHONE_HISTORY_DRAFT');await create(page,'HISTORY_PHONE_OTHER');
 await page.route(`**/v1/conversations/${a.id}`,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Original phone history failure'})}));await select(page,a.id);
 try{await expect(page.getByRole('button',{name:'重新读取这段对话',exact:true})).toBeInViewport();await expect(page.locator('.home-stage')).toHaveCount(0);await expect(page.locator('#send')).toBeDisabled();await expect(composer(page)).toHaveValue('PHONE_HISTORY_DRAFT')}finally{await page.screenshot({path:info.outputPath('history-read-phone-error.png'),fullPage:true})}
 await page.unroute(`**/v1/conversations/${a.id}`);await page.getByRole('button',{name:'重新读取这段对话',exact:true}).click();await expect(page.locator('article')).toContainText('HISTORY_PHONE_RETRY_TARGET');await expect(page.locator('#send')).toBeEnabled();await expect(composer(page)).toHaveValue('PHONE_HISTORY_DRAFT');
});

test('repeated opens share one owned read without restoring an older draft over typing',async({page})=>{
 await enter(page);const a=await create(page,'HISTORY_COALESCED_A');await composer(page).fill('COALESCED_SAVED_DRAFT');await create(page,'HISTORY_COALESCED_B');let entered,release;const waiting=new Promise(resolve=>entered=resolve),gate=new Promise(resolve=>release=resolve);let gets=0;
 await page.route(`**/v1/conversations/${a.id}`,async route=>{gets++;const response=await route.fetch();entered();await gate;await route.fulfill({response}).catch(()=>{})});
 try{await select(page,a.id);await waiting;await composer(page).fill('TYPED_DURING_SHARED_READ');await select(page,a.id);await frames(page);expect(gets).toBe(1);await expect(composer(page)).toHaveValue('TYPED_DURING_SHARED_READ');await expect(page.locator('#send')).toBeDisabled();release();await expect(page.locator('article')).toContainText('HISTORY_COALESCED_A');await expect(composer(page)).toHaveValue('TYPED_DURING_SHARED_READ');expect(gets).toBe(1)}finally{release()}
});

for(const kind of ['message','upload'])test(`accepted first ${kind} conversation survives initial read failure and retries only the same read`,async({page},info)=>{
 await enter(page);let creates=0,writes=0,selectedGets=0,createdId;page.on('request',r=>{const path=new URL(r.url()).pathname;if(r.method()==='POST'&&path==='/v1/conversations')creates++;if(r.method()==='POST'&&(path.endsWith('/events')||path==='/v1/sources'))writes++});
 await page.route('**/v1/conversations/*',async route=>{if(route.request().method()!=='GET'){await route.continue();return}selectedGets++;createdId=new URL(route.request().url()).pathname.split('/').pop();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Original first-read failure'})})});
 const text=kind==='message'?'2+2':'INDEPENDENT_FIRST_UPLOAD_DRAFT';await composer(page).fill(text);if(kind==='upload'){await page.getByLabel('上传文本文件').setInputFiles({name:'first-read-original.md',mimeType:'text/markdown',buffer:Buffer.from('FIRST_UPLOAD_BODY_NEVER_COMPOSER')});await page.getByRole('button',{name:'提交附件',exact:true}).click()}else await page.getByRole('button',{name:'发送',exact:true}).click();
 await expect(page.getByRole('button',{name:'重新读取这段对话',exact:true})).toBeEnabled();await expect(composer(page)).toHaveValue(text);await expect(page.locator('#send')).toBeDisabled();await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',createdId);expect(creates).toBe(1);expect(writes).toBe(0);expect(selectedGets).toBe(1);if(kind==='upload')await expect(page.locator('.staged-attachment')).toContainText('first-read-original.md');
 await page.screenshot({path:info.outputPath(`history-first-${kind}-read-failed.png`),fullPage:true});await page.unroute('**/v1/conversations/*');await page.getByRole('button',{name:'重新读取这段对话',exact:true}).click();await expect(page.locator('#send')).toBeEnabled();await expect(composer(page)).toHaveValue(text);expect(creates).toBe(1);expect(writes).toBe(0);
 await page.getByRole('button',{name:kind==='upload'?'提交附件':'发送',exact:true}).click();await expect(page.locator('article')).toHaveCount(1);await expect(page.getByRole('button',{name:'停止',exact:true})).toHaveCount(0);expect(creates).toBe(1);expect(writes).toBe(1);if(kind==='upload'){await expect(page.locator('.staged-attachment')).toHaveCount(0);await expect(composer(page)).toHaveValue(text)}else await expect(composer(page)).toHaveValue('');
});

test('superseding first-upload creation preserves its file separately from the actual composer draft',async({page})=>{
 await enter(page);const other=await create(page,'HISTORY_FIRST_UPLOAD_OTHER');await page.reload();await expect(composer(page)).toBeVisible();await expect(page.locator(`[data-conversation="${other.id}"]`)).toBeVisible();let createdId,entered,release;const waiting=new Promise(resolve=>entered=resolve),gate=new Promise(resolve=>release=resolve);let held=false,writes=0;
 await page.route('**/v1/conversations',async route=>{if(route.request().method()==='POST'){const response=await route.fetch();createdId=(await response.json()).id;await route.fulfill({response});return}if(createdId&&!held){held=true;const response=await route.fetch();entered();await gate;await route.fulfill({response}).catch(()=>{});return}await route.continue()});page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/v1/sources')writes++});
 try{await composer(page).fill('FIRST_UPLOAD_ACTUAL_DRAFT');await page.getByLabel('上传文本文件').setInputFiles({name:'superseded-original.md',mimeType:'text/markdown',buffer:Buffer.from('UPLOADED_BODY_MUST_NOT_SEED_COMPOSER')});await page.getByRole('button',{name:'提交附件',exact:true}).click();await waiting;await select(page,other.id);await expect(page.locator('article')).toContainText('HISTORY_FIRST_UPLOAD_OTHER');release();await expect(page.locator(`[data-conversation="${createdId}"]`)).toBeVisible();await select(page,createdId);await expect(composer(page)).toHaveValue('FIRST_UPLOAD_ACTUAL_DRAFT');await expect(page.locator('.staged-attachment')).toContainText('superseded-original.md');expect(writes).toBe(0);await expect(page.locator('#send')).toBeEnabled();await page.getByRole('button',{name:'提交附件',exact:true}).click();await expect(page.locator('article')).toHaveCount(1);await expect(page.locator('.staged-attachment')).toHaveCount(0);await expect(composer(page)).toHaveValue('FIRST_UPLOAD_ACTUAL_DRAFT');expect(writes).toBe(1)}finally{release()}
});

test('an old successful history snapshot cannot replace the newer A to B to A body or draft',async({page})=>{
 await enter(page);const a=await create(page,'HISTORY_STALE_SUCCESS_A'),b=await create(page,'HISTORY_STALE_SUCCESS_B');let first=true,entered,release;const waiting=new Promise(resolve=>entered=resolve),gate=new Promise(resolve=>release=resolve);
 await page.route(`**/v1/conversations/${a.id}`,async route=>{if(!first){await route.continue();return}first=false;const response=await route.fetch(),body=(await response.text()).replaceAll('HISTORY_STALE_SUCCESS_A','STALE_SUCCESS_BODY_MUST_NOT_REAPPEAR');entered();await gate;await route.fulfill({response,body}).catch(()=>{})});
 try{await select(page,a.id);await waiting;await select(page,b.id);await expect(page.locator('article')).toContainText('HISTORY_STALE_SUCCESS_B');await select(page,a.id);await expect(page.locator('article')).toContainText('HISTORY_STALE_SUCCESS_A');await composer(page).fill('NEWEST_A_DRAFT');release();await frames(page);await expect(page.locator('.messages')).not.toContainText('STALE_SUCCESS_BODY_MUST_NOT_REAPPEAR');await expect(composer(page)).toHaveValue('NEWEST_A_DRAFT');await expect(page.getByRole('alert')).toHaveCount(0)}finally{release()}
});

test('a selected reader hands controller ownership to its run watch and newer navigation cancels that watch',async({page})=>{
 await page.addInitScript(()=>{window.__trackSelectedWatch=false;window.__selectedWatchAborts=0;const fetchOriginal=window.fetch.bind(window);window.fetch=(url,options)=>{if(window.__trackSelectedWatch&&/\/v1\/runs\/[^/]+\/events\?/.test(String(url)))options?.signal?.addEventListener('abort',()=>window.__selectedWatchAborts++,{once:true});return fetchOriginal(url,options)}});
 await enter(page);const a=await create(page,'HISTORY_WATCH_HANDOFF_A'),b=await create(page,'HISTORY_WATCH_HANDOFF_B');let entered,release;const waiting=new Promise(resolve=>entered=resolve),gate=new Promise(resolve=>release=resolve);let first=true;
 await page.route(`**/v1/conversations/${a.id}`,async route=>{const response=await route.fetch();if(!first){await route.fulfill({response});return}first=false;const state=await response.json();state.runs[0].pending=true;await route.fulfill({response,json:state})});
 await page.route(`**/v1/runs/${a.run}/events?*`,async route=>{entered();await gate;await route.fulfill({status:503,body:'Original obsolete watch failure'}).catch(()=>{})});
 try{await page.evaluate(()=>window.__trackSelectedWatch=true);await select(page,a.id);await waiting;await frames(page);expect(await page.evaluate(()=>window.__selectedWatchAborts)).toBe(0);await expect(page.getByRole('button',{name:'停止',exact:true})).toBeVisible();await select(page,b.id);await expect(page.locator('article')).toContainText('HISTORY_WATCH_HANDOFF_B');await expect.poll(()=>page.evaluate(()=>window.__selectedWatchAborts)).toBe(1);await select(page,a.id);await expect(page.locator('article')).toContainText('HISTORY_WATCH_HANDOFF_A');release();await frames(page);await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByRole('button',{name:'停止',exact:true})).toHaveCount(0)}finally{release()}
});

test('a held Stop recovery read cannot clear a newer A watch or steal focus after A to B to A',async({page})=>{
 await enter(page);const a=await create(page,'HISTORY_STOP_FENCE_A'),b=await create(page,'HISTORY_STOP_FENCE_B');let gets=0,entered,release,releaseStreams;const waiting=new Promise(resolve=>entered=resolve),gate=new Promise(resolve=>release=resolve),streamGate=new Promise(resolve=>releaseStreams=resolve);
 await page.route(`**/v1/conversations/${a.id}`,async route=>{gets++;const response=await route.fetch(),state=await response.json();if(gets===2){entered();await gate;await route.fulfill({response,json:state}).catch(()=>{});return}state.runs[0].pending=true;await route.fulfill({response,json:state})});await page.route(`**/v1/runs/${a.run}/cancel`,route=>route.fulfill({status:200,contentType:'application/json',body:'{}'}));await page.route(`**/v1/runs/${a.run}/events?*`,async route=>{await streamGate;await route.abort().catch(()=>{})});
 try{await select(page,a.id);await page.getByRole('button',{name:'停止',exact:true}).click();await waiting;await select(page,b.id);await expect(page.locator('article')).toContainText('HISTORY_STOP_FENCE_B');await select(page,a.id);await expect(page.getByRole('button',{name:'停止',exact:true})).toBeVisible();const more=page.getByLabel('更多消息操作');await more.focus();release();await frames(page);await expect(page.getByRole('button',{name:'停止',exact:true})).toBeVisible();await expect(more).toBeFocused();await expect(page.getByRole('alert')).toHaveCount(0)}finally{release();releaseStreams()}
});
