import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {mkdirSync} from 'node:fs';
async function send(page,text){await page.getByLabel('消息',{exact:true}).fill(text);await page.getByRole('button',{name:'发送',exact:true}).click();await expect(page.getByLabel('消息',{exact:true})).toHaveValue('');await expect(page.getByRole('button',{name:'停止',exact:true})).toHaveCount(0)}
async function inspect(page,index='last'){const article=index==='first'?page.locator('article').first():page.locator('article').last();await article.getByLabel('更多消息操作').click();await article.getByRole('button',{name:'在 Lab 检查',exact:true}).click();return page.getByRole('dialog',{name:'HCL Lab'})}
test('local Inspector remains on selected historical run and read/export causes no execution',async({page})=>{
 await page.goto('/');await send(page,'2+2');const first=await page.locator('article').first().getAttribute('data-run');await send(page,'报告[原创纸灯]：周五开幕');const c=await page.locator('.chat-workspace').getAttribute('data-current-conversation');const before=await(await page.request.get(`/v1/conversations/${c}`)).json();const lab=await inspect(page,'first');await expect(lab.locator('[data-inspection-run]')).toHaveAttribute('data-inspection-run',first);await expect(lab).toContainText('本次未选择专门操作');await expect(lab.getByRole('button',{name:/Compare/})).toHaveCount(0);await lab.getByText('运行身份、路由与版本',{exact:true}).click();await expect(lab.getByText(first,{exact:true})).toBeVisible();await lab.getByText('Research Compare 的能力门槛',{exact:true}).click();await expect(lab).toContainText('没有合格双侧运行时不生成对比结果');const waiting=page.waitForEvent('download');await lab.getByRole('button',{name:'导出当前权限下的 mock 记录'}).click();const file=await waiting;const result=JSON.parse(await readFile(await file.path(),'utf8'));expect(result.run.run_id).toBe(first);expect(result.compare_enabled).toBe(false);const after=await(await page.request.get(`/v1/conversations/${c}`)).json();expect(after.state_version).toBe(before.state_version);expect(after.runs.map(r=>r.run_receipt.usage)).toEqual(before.runs.map(r=>r.run_receipt.usage));await page.keyboard.press('Escape');await expect(page.locator('article').first().getByRole('button',{name:'在 Lab 检查',exact:true})).toBeFocused();
});
test('Pages uses shared readable Inspector without fabricated runtime receipts or backend requests',async({page})=>{
 const backend=[];page.on('request',r=>{if(r.url().includes('/v1/'))backend.push(r.url())});await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4174/');await send(page,'记录：原创纸灯静态背景');const lab=await inspect(page);await expect(lab).toContainText('只读静态演示记录');await expect(lab).toContainText('未记录操作回执');await lab.getByText('Usage 与费用记录',{exact:true}).click();await expect(lab).toContainText('STATIC_PROVIDER_FREE_BOUNDARY');expect(backend).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);mkdirSync('.tmp/screenshots',{recursive:true});await page.screenshot({path:'.tmp/screenshots/pages-inspector-narrow.png',fullPage:true});
});
test('local delayed Inspector export cannot survive a cross-tab source deletion',async({page,context})=>{
 await page.goto('/');await send(page,'报告[原创纸灯]：P103_LAB_REVOKED_CANARY');const c=await page.locator('.chat-workspace').getAttribute('data-current-conversation');const other=await context.newPage();await other.goto('/');await other.locator(`[data-conversation="${c}"]`).click();const lab=await inspect(page);await expect(lab).toContainText('P103_LAB_REVOKED_CANARY');let captured,release,handled;const waiting=new Promise(r=>captured=r),gate=new Promise(r=>release=r),finished=new Promise(r=>handled=r);await page.route('**/v1/lab/export/*',async route=>{const response=await route.fetch();captured();await gate;try{await route.fulfill({response})}catch{}finally{handled()}});const downloads=[];page.on('download',d=>downloads.push(d));await lab.getByRole('button',{name:'导出当前权限下的 mock 记录'}).click();await waiting;await other.getByRole('button',{name:'记忆管理',exact:true}).click();await other.locator('.memory-card').filter({hasText:'P103_LAB_REVOKED_CANARY'}).getByRole('button',{name:'删除',exact:true}).click();await expect(page.getByRole('dialog',{name:'HCL Lab'})).toHaveCount(0);release();await finished;await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));expect(downloads).toHaveLength(0);expect(await page.locator('body').textContent()).not.toContain('P103_LAB_REVOKED_CANARY');await other.close();
});
for(const surface of ['local','pages'])test(`${surface} original late disclosure and conflicting reports retain uncertainty through inspection and recovery`,async({page})=>{
 const url=surface==='local'?'/':'http://127.0.0.1:4174/',prefix=surface==='local'?'报告[原创岚]：':'记录：';await page.goto(url);await send(page,prefix+'原创灯会周三改期，岚周五才收到消息');await send(page,(surface==='local'?'报告[原创林]：':'记录：')+'原创入口有人说在东侧');await send(page,(surface==='local'?'猜测[原创乔]：':'猜测：')+'原创入口也可能在西侧，尚待核对');const id=await page.locator('.chat-workspace').getAttribute('data-current-conversation');const lab=await inspect(page);await expect(lab).toContainText('不证明');await expect(lab).toContainText('NOT_TESTED');await expect(lab).toContainText('原创');await page.keyboard.press('Escape');await page.reload();if(surface==='local')await page.locator(`[data-conversation="${id}"]`).click();await expect(page.locator('article')).toHaveCount(3);const recovered=await inspect(page);await expect(recovered).toContainText('仅展示本次显式记录');if(surface==='local'){const state=await(await page.request.get(`/v1/context?conversation_id=${id}`)).json();const late=state.records.find(r=>r.content.includes('周五才收到'));expect(late.person_access_events).toEqual([]);expect(late.valid_time.start).toBe(null);const guess=state.records.find(r=>r.content.includes('西侧'));expect(guess.kind).toBe('USER_GUESS')}else await expect(recovered).toContainText('Browser-only');
});
