import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const pages='http://127.0.0.1:4174/';
async function send(page,text){await page.getByLabel('消息',{exact:true}).fill(text);await page.getByRole('button',{name:'发送',exact:true}).click();await expect(page.getByLabel('消息',{exact:true})).toHaveValue('');}
for(const surface of ['local','pages']){
 const url=surface==='local'?'/':pages,report=text=>surface==='local'?'报告[榛]：'+text:'记录：'+text;
 test(`${surface} answer evidence source return correction and historical search`,async({page})=>{
  await page.goto(url);await send(page,report('ORIGINAL_LOOP_THURSDAY'));if(surface==='pages')await send(page,'演示：查看当前背景');const historicalRun=await page.locator('article').last().getAttribute('data-run');
  await page.getByRole('button',{name:'查看依据',exact:true}).last().click();await expect(page.getByRole('dialog')).toHaveCount(1);await page.getByRole('button',{name:/查看来源 v/}).first().click();await expect(page.getByRole('dialog',{name:'原文'})).toContainText('ORIGINAL_LOOP_THURSDAY');await expect(page.getByRole('dialog')).toHaveCount(1);await page.getByRole('button',{name:'返回依据'}).click();await expect(page.getByRole('dialog',{name:'查看依据'})).toContainText('ORIGINAL_LOOP_THURSDAY');await expect(page.getByRole('button',{name:/查看来源 v/}).first()).toBeFocused();
  await page.getByRole('button',{name:'纠正或管理背景'}).click();const row=page.locator('.memory-card').filter({hasText:'ORIGINAL_LOOP_THURSDAY'}).filter({hasText:'ACTIVE'});await row.getByRole('button',{name:'内容不对',exact:true}).click();await page.getByLabel('修订值').fill('CORRECTED_LOOP_FRIDAY');await page.getByRole('button',{name:'提交更正并更新回答'}).click();await expect(page.getByLabel('修订值')).toHaveCount(0);await page.getByRole('button',{name:'关闭记忆管理'}).click();await page.getByRole('button',{name:'查看变化',exact:true}).last().click();await expect(page.getByRole('dialog',{name:'理解变化'})).toContainText('ORIGINAL_LOOP_THURSDAY');await expect(page.getByRole('dialog',{name:'理解变化'})).toContainText('CORRECTED_LOOP_FRIDAY');await page.getByRole('button',{name:'关闭理解变化'}).click();
  await page.locator(`[data-run="${historicalRun}"]`).getByRole('button',{name:'查看依据',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('ORIGINAL_LOOP_THURSDAY');await page.getByRole('button',{name:'关闭查看依据'}).click();
  await page.getByRole('button',{name:'搜索对话',exact:true}).click();await page.getByLabel('搜索历史').fill('ORIGINAL_LOOP_THURSDAY');await expect(page.locator('.search-hit').first()).toContainText('ORIGINAL_LOOP_THURSDAY');await page.locator('.search-hit').first().getByText('同会话更正与撤回',{exact:true}).click();await expect(page.locator('.search-hit').first()).toContainText('CORRECTED_LOOP_FRIDAY');await page.locator('.search-hit').first().getByRole('button').first().click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('article').first()).toBeFocused();
 });
 test(`${surface} current change guess hypothesis and permission-aware export/delete`,async({page})=>{
  await page.goto(url);await send(page,report('ORIGINAL_ACTUAL_BLUE'));await page.getByRole('button',{name:'记忆管理',exact:true}).click();let row=page.locator('.memory-card').filter({hasText:'ORIGINAL_ACTUAL_BLUE'}).filter({hasText:'ACTIVE'});
  await row.getByRole('button',{name:'假设另一种情况',exact:true}).click();await page.getByLabel('修订值').fill('HYPOTHETICAL_WHITE_ONLY');await page.getByRole('button',{name:'提交更正并更新回答'}).click();await expect(page.getByLabel('修订值')).toHaveCount(0);await page.getByRole('button',{name:'关闭记忆管理'}).click();
  await send(page,surface==='pages'?'演示：查看当前背景':report('独立真实场景继续'));await expect(page.locator('article').last()).not.toContainText('HYPOTHETICAL_WHITE_ONLY');await page.getByRole('button',{name:'记忆管理',exact:true}).click();row=page.locator('.memory-card').filter({hasText:'ORIGINAL_ACTUAL_BLUE'}).filter({hasText:'ACTIVE'});await row.getByRole('button',{name:'从现在变化',exact:true}).click();await page.getByLabel('修订值').fill('CURRENT_BLUE_REVISED');await page.getByRole('button',{name:'提交更正并更新回答'}).click();await expect(page.getByLabel('修订值')).toHaveCount(0);
  row=page.locator('.memory-card').filter({hasText:'CURRENT_BLUE_REVISED'}).filter({hasText:'ACTIVE'});await row.getByRole('button',{name:'这只是猜测',exact:true}).click();await expect(page.locator('.memory-card').filter({hasText:'CURRENT_BLUE_REVISED'}).filter({hasText:surface==='local'?'用户猜测':'USER_GUESS'})).toBeVisible();await page.getByRole('button',{name:'关闭记忆管理'}).click();
  await page.getByRole('button',{name:'设置',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出当前会话'}).click();const file=await download;const exported=await readFile(await file.path(),'utf8');expect(exported).toContain('CURRENT_BLUE_REVISED');
  await page.getByRole('button',{name:'记忆管理',exact:true}).click();const old=page.locator('.memory-card').filter({hasText:'ORIGINAL_ACTUAL_BLUE'}).first();await old.getByRole('button',{name:'删除',exact:true}).click();await page.getByRole('button',{name:'关闭记忆管理'}).click();await page.getByRole('button',{name:'搜索对话',exact:true}).click();await page.getByLabel('搜索历史').fill('ORIGINAL_ACTUAL_BLUE');await expect(page.locator('.search-hit')).toHaveCount(0);await page.getByRole('button',{name:'关闭搜索对话'}).click();await page.getByRole('button',{name:'设置',exact:true}).click();const cleaned=page.waitForEvent('download');await page.getByRole('button',{name:'导出当前会话'}).click();const clean=await cleaned;expect(await readFile(await clean.path(),'utf8')).not.toContain('ORIGINAL_ACTUAL_BLUE');
 });
}
test('local stale export response is cancelled after another tab deletes its source',async({page,context})=>{
 await page.goto('/');await send(page,'报告[榛]：EXPORT_REVOKED_ORIGINAL_CANARY');await expect(page.locator('.assistant-message')).toContainText('先核对');const id=await page.locator('.chat-workspace').getAttribute('data-current-conversation');const other=await context.newPage();await other.goto('/');await other.locator(`[data-conversation="${id}"]`).click();await expect(other.locator('.assistant-message')).toContainText('EXPORT_REVOKED_ORIGINAL_CANARY');
 let captured,release,first=true;const waiting=new Promise(r=>captured=r),gate=new Promise(r=>release=r);await page.route(`**/v1/conversations/${id}`,async route=>{if(!first){await route.continue();return}first=false;const response=await route.fetch();captured();await gate;await route.fulfill({response})});const downloads=[];page.on('download',d=>downloads.push(d));await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'导出当前会话'}).click();await waiting;
 await other.getByRole('button',{name:'记忆管理',exact:true}).click();await other.locator('.memory-card').filter({hasText:'EXPORT_REVOKED_ORIGINAL_CANARY'}).getByRole('button',{name:'删除',exact:true}).click();await expect(other.locator('.memory-card').filter({hasText:'EXPORT_REVOKED_ORIGINAL_CANARY'})).toHaveCount(0);await expect(page.locator('.messages')).not.toContainText('EXPORT_REVOKED_ORIGINAL_CANARY');release();await expect(page.getByRole('alert')).toContainText('导出已取消');expect(downloads).toHaveLength(0);await other.close();
});
test('Pages identical correction does not manufacture an important change',async({page})=>{
 await page.goto(pages);await send(page,'记录：P1_SAME_CONTENT_BROWSER');await page.getByRole('button',{name:'记忆管理',exact:true}).click();await page.locator('.memory-card').filter({hasText:'P1_SAME_CONTENT_BROWSER'}).getByRole('button',{name:'内容不对',exact:true}).click();await page.getByRole('button',{name:'提交更正并更新回答'}).click();await expect(page.getByLabel('修订值')).toHaveCount(0);await page.getByRole('button',{name:'关闭记忆管理'}).click();await expect(page.locator('article').last()).toContainText('没有变化');await expect(page.getByRole('button',{name:'查看变化',exact:true})).toHaveCount(0);
});
for(const surface of ['local','pages'])test(`${surface} delete purges attachment filename cache`,async({page})=>{
 await page.goto(surface==='local'?'/':pages);const name='DELETE_ATTACHMENT_NAME_CANARY.md';await page.getByLabel('上传文本文件').setInputFiles({name,mimeType:'text/markdown',buffer:Buffer.from('ORIGINAL_ATTACHMENT_DELETE_BODY')});await page.getByRole('button',{name:'提交附件',exact:true}).click();await expect(page.locator('.staged-attachment')).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:name})).toContainText('已完整登记');await page.getByRole('button',{name:'记忆管理',exact:true}).click();const row=page.locator('.memory-card').filter({hasText:name});await row.getByRole('button',{name:surface==='local'?'删除文件':'删除',exact:true}).click();await expect(row).toHaveCount(0);await page.getByRole('button',{name:'关闭记忆管理'}).click();await expect(page.locator('body')).not.toContainText(name);await expect(page.locator('.messages')).not.toContainText('ORIGINAL_ATTACHMENT_DELETE_BODY');
});
