import {test,expect} from '@playwright/test';
test.use({trace:'retain-on-failure',screenshot:'only-on-failure'});
async function create(page){const response=page.waitForResponse(r=>r.url().endsWith('/v1/conversations')&&r.request().method()==='POST');await page.getByRole('button',{name:'＋ 新对话',exact:true}).click();const id=(await(await response).json()).id;await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',id);await expect(page.getByLabel('消息',{exact:true})).toBeFocused();return id}
async function enter(page){await page.goto('/');await expect(page.getByLabel('消息',{exact:true})).toBeVisible();return create(page)}
async function holdReconciliation(page,id){
 let committed=false,first=true,entered,release;const waiting=new Promise(resolve=>entered=resolve),gate=new Promise(resolve=>release=resolve),keys=[];
 await page.route(`**/v1/conversations/${id}/events`,async route=>{keys.push(route.request().postDataJSON().idempotency_key);if(first){first=false;await route.fetch();committed=true;await route.abort('failed')}else await route.continue()});
 await page.route(`**/v1/conversations/${id}`,async route=>{if(!committed){await route.continue();return}committed=false;const response=await route.fetch();entered();await gate;await route.fulfill({response}).catch(()=>{})});return {waiting,release,keys};
}
for(const mode of ['release','timeout'])test(`lost acknowledgement keeps retry unavailable until read-only reconciliation ${mode}`,async({page},info)=>{
 const id=await enter(page),held=await holdReconciliation(page,id),composer=page.getByLabel('消息',{exact:true});
 try{await composer.fill('2+2');await composer.press('Enter');await held.waiting;await expect(page.getByRole('alert')).toContainText('连接暂时中断，草稿已保留');await expect(composer).toHaveValue('2+2');await expect(page.locator('#send')).toBeDisabled();await expect(page.locator('#send')).toHaveText('正在核对');await expect(page.getByRole('button',{name:'停止',exact:true})).toHaveCount(0);expect(held.keys).toHaveLength(1);await expect(page.getByRole('alert')).toContainText('正在核对提交状态');if(mode==='timeout'){await expect(page.getByRole('button',{name:'发送',exact:true})).toBeEnabled({timeout:18000});expect(held.keys).toHaveLength(1);await expect(composer).toHaveValue('2+2')}}finally{await page.screenshot({path:info.outputPath(`reconciliation-${mode==='timeout'?'timed-out':'pending'}.png`),fullPage:true});held.release()}
 await expect(page.getByRole('button',{name:'发送',exact:true})).toBeEnabled();await page.getByRole('button',{name:'发送',exact:true}).click();await expect(composer).toHaveValue('');expect(held.keys).toHaveLength(2);expect(held.keys[1]).toBe(held.keys[0]);const state=await(await page.request.get(`/v1/conversations/${id}`)).json();expect(state.events).toHaveLength(1);expect(state.runs).toHaveLength(1);
});
test('navigation aborts an old reconciliation before presenting an actionable send in another conversation',async({page},info)=>{
 const old=await enter(page),next=await create(page);await page.locator(`[data-conversation="${old}"]`).click();await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',old);await expect(page.getByLabel('消息',{exact:true})).toBeFocused();const held=await holdReconciliation(page,old),composer=page.getByLabel('消息',{exact:true});let nextPosts=0;page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith(`/v1/conversations/${next}/events`))nextPosts++});
 try{await composer.fill('2+2');await composer.press('Enter');await held.waiting;await page.locator(`[data-conversation="${next}"]`).click();await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',next);await composer.fill('3+3');await page.getByRole('button',{name:'发送',exact:true}).click();await expect.poll(()=>nextPosts).toBe(1);await expect(composer).toHaveValue('')}finally{held.release()}
 await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',next);await expect(page.locator('.messages')).toContainText('3+3');await expect(page.locator('.messages')).not.toContainText('2+2');expect(nextPosts).toBe(1);await page.screenshot({path:info.outputPath('reconciliation-new-conversation.png'),fullPage:true});
});

test('a late failure from an older A to B to A visit cannot replace the reloaded conversation state',async({page})=>{
 const old=await enter(page),other=await create(page);await page.locator(`[data-conversation="${old}"]`).click();await expect(page.getByLabel('消息',{exact:true})).toBeFocused();let entered,release;const waiting=new Promise(resolve=>entered=resolve),gate=new Promise(resolve=>release=resolve);let writes=0;
 await page.route(`**/v1/conversations/${old}/events`,async route=>{writes++;await route.fetch();entered();await gate;await route.abort('failed')});
 try{await page.getByLabel('消息',{exact:true}).fill('2+2');await page.getByLabel('消息',{exact:true}).press('Enter');await waiting;await page.locator(`[data-conversation="${other}"]`).click();await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',other);await page.locator(`[data-conversation="${old}"]`).click();await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',old);await expect(page.locator('article')).toHaveCount(1);
  const failed=page.waitForEvent('requestfailed',request=>request.method()==='POST'&&request.url().endsWith(`/v1/conversations/${old}/events`));release();await failed;await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await expect(page.getByRole('alert')).toHaveCount(0);expect(writes).toBe(1);await expect(page.locator('article')).toHaveCount(1);
 }finally{release()}
});

test('a failed new-conversation intent releases old reconciliation and preserves the original draft for explicit retry',async({page})=>{
 const id=await enter(page),held=await holdReconciliation(page,id),composer=page.getByLabel('消息',{exact:true});let creates=0;
 await page.route('**/v1/conversations',async route=>{if(route.request().method()==='POST'){creates++;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Original injected creation outage'})})}else await route.continue()});
 try{await composer.fill('2+2');await composer.press('Enter');await held.waiting;await expect(page.locator('#send')).toBeDisabled();await page.getByRole('button',{name:'＋ 新对话',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Original injected creation outage');await expect(page.getByRole('button',{name:'发送',exact:true})).toBeEnabled();await expect(composer).toHaveValue('2+2');await expect(page.locator('.chat-workspace')).toHaveAttribute('data-current-conversation',id);expect(creates).toBe(1);
  await page.getByRole('button',{name:'发送',exact:true}).click();await expect(composer).toHaveValue('');expect(held.keys).toHaveLength(2);expect(held.keys[1]).toBe(held.keys[0]);const state=await(await page.request.get(`/v1/conversations/${id}`)).json();expect(state.events).toHaveLength(1);
 }finally{held.release()}
});

test('a read failure after acknowledged send refers to the recorded input without claiming a cleared draft was retained',async({page},info)=>{
 const id=await enter(page);let failed=false,writes=0;page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith(`/v1/conversations/${id}/events`))writes++});
 await page.route(`**/v1/conversations/${id}`,async route=>{if(!failed){failed=true;await route.abort('failed')}else await route.continue()});const composer=page.getByLabel('消息',{exact:true});await composer.fill('2+2');await composer.press('Enter');await expect(composer).toHaveValue('');await expect(page.getByRole('alert')).toContainText('连接暂时中断，请查看已记录的输入');await expect(page.getByRole('alert')).not.toContainText('草稿已保留');await expect(page.locator('.messages')).toContainText('2+2');expect(writes).toBe(1);const state=await(await page.request.get(`/v1/conversations/${id}`)).json();expect(state.events).toHaveLength(1);await page.screenshot({path:info.outputPath('accepted-send-read-failure.png'),fullPage:true});
});
