import {STORAGE_KEY, LEGACY_KEY, emptyState, loadState, saveState, createConversation as createModelConversation, submit, changeRecord, resolveBasis, decodeFile} from './preview-model.js';
const $=id=>document.getElementById(id);
const withStorageLock=action=>{if(!navigator.locks)throw new Error('此浏览器无法安全协调多页面数据，请使用支持 Web Locks 的浏览器');return navigator.locks.request('hcl-assistant-preview-storage',action)};
let loadFailed=false;let state;try{state=await withStorageLock(()=>loadState(localStorage))}catch(error){loadFailed=true;state=emptyState();showError('保存的记录无法读取，未覆盖原数据：'+error.message)}
let currentId=state.currentId||null;let sidebarVisible=true;let busy=false;
function save(){state.currentId=currentId}
function current(){return state.conversations.find(c=>c.id===currentId)||null}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
async function commit(change){
 if(loadFailed||busy){showError(loadFailed?'存储不可用，原数据未覆盖。请先检查或重置演示数据。':'正在保存，请稍后重试');return false}
 busy=true;
 try{return await withStorageLock(()=>{const draft=JSON.parse(JSON.stringify(state));const result=change(draft);saveState(draft,localStorage);state=draft;currentId=state.currentId;render();return result||true})}
 catch(error){showError('操作未保存，原记录未改变：'+error.message);return false}
 finally{busy=false}
}
async function createConversation(){if(await commit(draft=>createModelConversation(draft,$('memoryScope').value,$('topicSelect').value)))$('composer').focus()}
async function addRun(input,meta={}){const target=currentId;const accepted=await commit(draft=>{let c=draft.conversations.find(x=>x.id===target);if(!c)c=createModelConversation(draft,$('memoryScope').value,$('topicSelect').value);return submit(draft,c.id,input,meta)});if(accepted)requestAnimationFrame(()=>{$('messages').scrollTop=$('messages').scrollHeight});return accepted}
window.addEventListener('storage',async event=>{
 if(![STORAGE_KEY,LEGACY_KEY,null].includes(event.key))return;
 try{await withStorageLock(()=>{const latest=loadState(localStorage);const temporary=state.conversations.filter(c=>c.memory==='TEMPORARY');state={...latest,conversations:[...temporary,...latest.conversations]};currentId=state.conversations.some(c=>c.id===currentId)?currentId:state.currentId;state.currentId=currentId;$('panel').close();render()})}
 catch(error){loadFailed=true;state=emptyState();currentId=null;$('panel').close();render();showError('其他页面的数据变更无法安全读取，请刷新：'+error.message)}
});
function render(){
 const c=current();$('conversationList').innerHTML=state.conversations.map(conv=>'<button data-conv="'+conv.id+'" aria-current="'+(conv.id===currentId)+'">'+escapeHtml(conv.title)+' · '+(conv.memory==='TEMPORARY'?'临时':'已保存')+'</button>').join('');
 $('conversationList').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{currentId=btn.dataset.conv;save();render()}));
 $('conversationTitle').textContent=c?c.title+(c.topic?' · Topic':''):'从一段对话开始';$('openMemory').disabled=!c;$('openLab').disabled=!(c&&c.runs.length);
 if(!c||!c.runs.length){$('messages').innerHTML='<section class="empty" id="emptyState"><h1>有什么想一起理清？</h1><p>这是静态合成预览。可以体验聊天、Explain、修订和 Lab 外壳，但不会调用真实 HCL 或模型。</p><div class="chips"><button data-prompt="2+2">算式演示</button><button data-prompt="记录：合成项目周五交稿">记录合成背景</button><button data-prompt="演示：查看当前背景">查看已选背景</button></div></section>';wireChips();return}
 $('messages').innerHTML=c.runs.map(run=>'<article><div class="message-meta"><span>状态版本 v'+run.version+'</span><span>'+run.route+' · MOCK</span></div><p class="user-message">'+escapeHtml(run.input)+'</p><p class="assistant-message">'+(run.legacyUnverified?'[旧版未验证模板，不代表真实依据] ':'')+escapeHtml(run.text)+'</p><div class="actions"><button data-explain="'+run.id+'">Explain</button><button data-lab="'+run.id+'">在 Lab 检查</button></div></article>').join('');
 $('messages').querySelectorAll('[data-explain]').forEach(btn=>btn.addEventListener('click',()=>showExplain(btn.dataset.explain)));$('messages').querySelectorAll('[data-lab]').forEach(btn=>btn.addEventListener('click',()=>showLab(btn.dataset.lab)))
}
function findRun(id){for(const c of state.conversations){const run=c.runs.find(r=>r.id===id);if(run)return{c,run}}return null}
function openPanel(html){$('panelContent').innerHTML=html;$('panel').showModal()}
function showExplain(id){const found=findRun(id);if(!found)return;const {c,run}=found;const basis=resolveBasis(c,run);openPanel('<h2>当次回答依据</h2><p class="notice">STATIC MOCK · 仅展示实际选取的记录，不是模型隐藏思维。</p><section><h3>为什么这样回答？</h3>'+(basis.length?'<ul>'+basis.map(x=>'<li>'+escapeHtml(x.recordId)+' · '+escapeHtml(x.status)+'<p>'+escapeHtml(x.content||'原文不可用')+'</p></li>').join('')+'</ul>':'<p>本次没有人物背景依据。</p>')+'</section><section><h3>关键限制</h3><p>'+escapeHtml(run.uncertainty)+'</p></section><section><h3>什么会改变判断？</h3><p>'+escapeHtml(run.change)+'</p></section><small>run '+run.id+' · snapshot v'+run.version+'</small>')}
function showLab(id){const found=findRun(id);if(!found)return;const {c,run}=found;openPanel('<h2>HCL Lab · 静态模拟记录</h2><p class="notice">未接入真实 HCL；成功运行不代表认知效力。</p><dl><dt>Route</dt><dd>'+escapeHtml(run.route)+'</dd><dt>State version</dt><dd>'+(run.version-1)+' → '+run.version+'</dd><dt>Selected capabilities</dt><dd>'+(run.caps.length?run.caps.map(c=>'<span class="tag">'+escapeHtml(c)+'</span>').join(''):'无专门操作')+'</dd><dt>Provider calls</dt><dd>0</dd></dl><h3>Recorded basis</h3><pre>'+escapeHtml(JSON.stringify({basis:resolveBasis(c,run),uncertainty:run.uncertainty,change_condition:run.change},null,2))+'</pre><button disabled>Base Compare（L3 后另需许可）</button>')}
function showMemory(){const c=current();if(!c)return;const rows=c.records.map(r=>'<div class="memory-row"><small>'+escapeHtml(r.id)+' · '+escapeHtml(r.kind)+' · '+escapeHtml(r.status)+' · v'+r.version+'</small><p>'+escapeHtml(r.content||'正文已删除')+'</p>'+(r.status==='ACTIVE'?'<button data-stop="'+r.id+'">停止使用</button><button data-guess="'+r.id+'">这只是猜测</button>':'')+(r.status!=='DELETED'?'<button data-delete="'+r.id+'">删除</button>':'')+'</div>').join('');openPanel('<h2>可管理的背景</h2><p>临时会话仅在内存，刷新后消失；其他会话保存在此浏览器。停止使用阻止后续背景选择；删除清理关联正文及派生回答。独立来源不会随之删除。</p>'+(rows||'<p>当前没有记录。</p>'));$('panelContent').querySelectorAll('[data-stop]').forEach(btn=>btn.addEventListener('click',()=>updateRecord(btn.dataset.stop,'STOPPED')));$('panelContent').querySelectorAll('[data-guess]').forEach(btn=>btn.addEventListener('click',()=>updateRecord(btn.dataset.guess,'GUESS')));$('panelContent').querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',()=>updateRecord(btn.dataset.delete,'DELETED')))}
async function updateRecord(id,action){if(await commit(draft=>changeRecord(draft,currentId,id,action)))showMemory()}
function wireChips(){document.querySelectorAll('[data-prompt]').forEach(btn=>btn.addEventListener('click',()=>{$('composer').value=btn.dataset.prompt;$('send').disabled=false;$('composer').focus()}))}
$('newConversation').addEventListener('click',createConversation);$('toggleSidebar').addEventListener('click',()=>{sidebarVisible=!sidebarVisible;$('app').classList.toggle('sidebar-hidden',!sidebarVisible)});$('composer').addEventListener('input',()=>{$('send').disabled=!$('composer').value.trim()});$('composer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229){e.preventDefault();if($('composer').value.trim())$('send').click()}});$('send').addEventListener('click',async()=>{const value=$('composer').value.trim();if(!value)return;if(await addRun(value)){$('composer').value='';$('send').disabled=true}});
$('fileInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const target=currentId;try{const file=decodeFile(f.name,new Uint8Array(await f.arrayBuffer()));if(currentId!==target)throw new Error('读取期间对话已切换，请重新选择文件');await addRun(file.content,{fileName:file.fileName,byteLength:file.byteLength})}catch(error){showError(error.message)}e.target.value=''});
$('openLab').addEventListener('click',()=>{const c=current();if(c?.runs.length)showLab(c.runs[c.runs.length-1].id)});$('openMemory').addEventListener('click',showMemory);$('closePanel').addEventListener('click',()=>$('panel').close());$('panel').addEventListener('cancel',e=>{e.preventDefault();$('panel').close()});$('resetPreview').addEventListener('click',async()=>{if(confirm('清空这个浏览器中的 HCL Assistant Preview 数据？')){try{await withStorageLock(()=>{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(LEGACY_KEY);state=emptyState();loadFailed=false;currentId=null;render()})}catch(error){showError('重置失败：'+error.message)}}});$('memoryScope').addEventListener('change',()=>{$('topicSelect').disabled=$('memoryScope').value==='TEMPORARY'});function showError(message){$('error').textContent=message;$('error').hidden=false}
render();
