const STORAGE_KEY='hcl-assistant-pages-preview-v1';
const $=id=>document.getElementById(id);
const state=loadState();let currentId=state.currentId||null;let sidebarVisible=true;

function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{conversations:[],currentId:null}}catch{return{conversations:[],currentId:null}}}
function save(){state.currentId=currentId;localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function current(){return state.conversations.find(c=>c.id===currentId)||null}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function classify(text){if(/猜|可能|我觉得|我怀疑/.test(text))return'USER_GUESS';if(/更正|不是|说错|改一下/.test(text))return'CORRECTION';return'USER_REPORTED_EVENT'}
function synthesize(text){
 const t=text.trim();
 if(/2\s*\+\s*2/.test(t))return{text:'4。',route:'DIRECT',caps:[],basis:[],uncertainty:'本题不需要人物或关系认知处理。',change:'无。'};
 if(/不回|关系|冲突|在乎|主动来找/.test(t))return{text:'现在更稳妥的判断是：不要把单次沉默直接理解成“不在乎”。如果前面确实存在没有说开的冲突，回避那场冲突会是一个值得保留的解释；但它仍取决于对方当时是否已经知道相关情况。',route:'CONTEXT_ASSISTED',caps:['competing_explanations','perspective_state'],basis:['用户报告的互动变化','当前会话中与冲突相关的已知背景'],uncertainty:'动机仍不能由一次行为单独确定。',change:'如果后来确认对方当时并不知情，“有意回避冲突”的解释应明显减弱。'};
 if(/忠诚|概念|价值|事实.*争|争论/.test(t))return{text:'这更像是需要先拆开三个层面：你们是否对事实本身有分歧、对“忠诚”这样的概念判据是否不同，以及即使概念相近，价值优先级是否不同。把三者混在一起，会让争论看起来像同一个问题。',route:'SELECTED_COGNITION',caps:['concept_comparison','competing_explanations'],basis:['当前问题明确要求区分事实、概念与价值层'],uncertainty:'没有更多双方原话时，不能替任何一方固定唯一概念定义。',change:'加入双方各自对“忠诚”的明确表述后，可以更新局部 reading，而不改写已经发生的事实。'};
 if(/责任|风险|知道|知情/.test(t))return{text:'如果 A 是决定之后才第一次知道风险，那么依赖“决策前知情”的责任判断需要撤回或减弱；但这并不会自动消除其他可能的责任条件，例如控制能力、职责或是否存在别的可避免行为。',route:'SELECTED_COGNITION',caps:['responsibility_conditions','information_access'],basis:['用户给出的知情时间变化','责任判断需要区分知识与其他条件'],uncertainty:'这里只能调整依赖该前提的部分，不能据此推出“完全无责任”。',change:'把首次获知时间改回决策前，会重新激活相关知情条件。'};
 if(/更正|不是|说错|改一下/.test(t))return{text:'这个补充应该作为更正处理，而不是简单追加一条新事实。依赖旧说法的解释应停止沿用，但与这次更正无关的记录仍保留。',route:'CONTEXT_ASSISTED',caps:['narrative_revision'],basis:['当前消息包含显式更正信号'],uncertainty:'静态预览不会自动解析任意复杂指代；这里只演示修订语义。',change:'更正后的后续回答会优先使用新记录，旧回答仍保留为历史。'};
 return{text:'我会先把你这句话作为当前会话的一条记录，而不是自动把其中的解释都当成事实。这个 GitHub Pages 版本只演示 HCL Assistant 的产品交互；它没有接入真实 HCL，也不会调用模型。',route:'CONTEXT_ASSISTED',caps:[],basis:['当前用户消息'],uncertainty:'任意自然语言的真实语义理解尚未在这个静态预览中实现。',change:'补充、更正或撤回信息时，预览会保留新的状态版本。'}
}
function createConversation(){const id=uid('conv'),memory=$('memoryScope').value,topic=memory==='TEMPORARY'?'':$('topicSelect').value;state.conversations.unshift({id,title:'新对话',memory,topic,version:0,runs:[],records:[]});currentId=id;save();render();$('composer').focus()}
function addRun(input,meta={}){
 let c=current();if(!c){createConversation();c=current()}c.version+=1;if(c.title==='新对话')c.title=input.slice(0,22)||'新对话';
 const kind=classify(input),record={id:uid('record'),kind,content:input,status:'ACTIVE',version:c.version};
 if(kind==='CORRECTION'&&c.records.length){const prior=[...c.records].reverse().find(r=>r.status==='ACTIVE'&&r.kind!=='CORRECTION');if(prior)prior.status='SUPERSEDED'}
 c.records.push(record);const result=synthesize(input);c.runs.push({id:uid('run'),input,kind,recordId:record.id,version:c.version,createdAt:new Date().toISOString(),...result,...meta});save();render();requestAnimationFrame(()=>{$('messages').scrollTop=$('messages').scrollHeight})
}
function render(){
 const c=current();$('conversationList').innerHTML=state.conversations.map(conv=>'<button data-conv="'+conv.id+'" aria-current="'+(conv.id===currentId)+'">'+escapeHtml(conv.title)+' · '+(conv.memory==='TEMPORARY'?'临时':'已保存')+'</button>').join('');
 $('conversationList').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{currentId=btn.dataset.conv;save();render()}));
 $('conversationTitle').textContent=c?c.title+(c.topic?' · Topic':''):'从一段对话开始';$('openMemory').disabled=!c;$('openLab').disabled=!(c&&c.runs.length);
 if(!c||!c.runs.length){$('messages').innerHTML='<section class="empty" id="emptyState"><h1>有什么想一起理清？</h1><p>这是静态合成预览。可以体验聊天、Explain、修订和 Lab 外壳，但不会调用真实 HCL 或模型。</p><div class="chips"><button data-prompt="她昨晚说没事，今天又不回我，她到底是什么意思？">关系理解</button><button data-prompt="我们争论的到底是事实、忠诚这个概念，还是价值优先级？">概念分歧</button><button data-prompt="如果 A 是决定之后才知道风险，这会怎样改变责任判断？">迟到信息</button></div></section>';wireChips();return}
 $('messages').innerHTML=c.runs.map(run=>'<article><div class="message-meta"><span>状态版本 v'+run.version+'</span><span>'+run.route+' · MOCK</span></div><p class="user-message">'+escapeHtml(run.input)+'</p><p class="assistant-message">'+escapeHtml(run.text)+'</p><div class="actions"><button data-explain="'+run.id+'">Explain</button><button data-lab="'+run.id+'">在 Lab 检查</button></div></article>').join('');
 $('messages').querySelectorAll('[data-explain]').forEach(btn=>btn.addEventListener('click',()=>showExplain(btn.dataset.explain)));$('messages').querySelectorAll('[data-lab]').forEach(btn=>btn.addEventListener('click',()=>showLab(btn.dataset.lab)))
}
function findRun(id){for(const c of state.conversations){const run=c.runs.find(r=>r.id===id);if(run)return{c,run}}return null}
function openPanel(html){$('panelContent').innerHTML=html;$('panel').showModal()}
function showExplain(id){const found=findRun(id);if(!found)return;const {run}=found;openPanel('<h2>当次回答依据</h2><p class="notice">STATIC MOCK · 展示的是预先记录的显式依据，不是模型隐藏思维。</p><section><h3>为什么这样回答？</h3>'+(run.basis.length?'<ul>'+run.basis.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ul>':'<p>本次没有人物背景依据。</p>')+'</section><section><h3>关键限制</h3><p>'+escapeHtml(run.uncertainty)+'</p></section><section><h3>什么会改变判断？</h3><p>'+escapeHtml(run.change)+'</p></section><small>run '+run.id+' · snapshot v'+run.version+'</small>')}
function showLab(id){const found=findRun(id);if(!found)return;const {run}=found;openPanel('<h2>HCL Lab · 静态模拟记录</h2><p class="notice">未接入真实 HCL；成功运行不代表认知效力。</p><dl><dt>Route</dt><dd>'+escapeHtml(run.route)+'</dd><dt>State version</dt><dd>'+(run.version-1)+' → '+run.version+'</dd><dt>Selected capabilities</dt><dd>'+(run.caps.length?run.caps.map(c=>'<span class="tag">'+escapeHtml(c)+'</span>').join(''):'无专门操作')+'</dd><dt>Provider calls</dt><dd>0</dd></dl><h3>Recorded basis</h3><pre>'+escapeHtml(JSON.stringify({basis:run.basis,uncertainty:run.uncertainty,change_condition:run.change},null,2))+'</pre><button disabled>Base Compare（L3 后另需许可）</button>')}
function showMemory(){const c=current();if(!c)return;const rows=c.records.map(r=>'<div class="memory-row"><small>'+escapeHtml(r.kind)+' · '+escapeHtml(r.status)+' · v'+r.version+'</small><p>'+escapeHtml(r.content)+'</p>'+(r.status==='ACTIVE'?'<button data-stop="'+r.id+'">停止使用</button><button data-guess="'+r.id+'">这只是猜测</button>':'')+'<button data-delete="'+r.id+'">删除</button></div>').join('');openPanel('<h2>可管理的背景</h2><p>Pages 预览中的记录只存在当前浏览器 localStorage。</p>'+(rows||'<p>当前没有记录。</p>'));$('panelContent').querySelectorAll('[data-stop]').forEach(btn=>btn.addEventListener('click',()=>updateRecord(btn.dataset.stop,'STOPPED')));$('panelContent').querySelectorAll('[data-guess]').forEach(btn=>btn.addEventListener('click',()=>updateRecord(btn.dataset.guess,'GUESS')));$('panelContent').querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',()=>updateRecord(btn.dataset.delete,'DELETED')))}
function updateRecord(id,action){const c=current(),r=c?.records.find(x=>x.id===id);if(!r)return;if(action==='STOPPED')r.status='STOPPED';if(action==='GUESS'){r.kind='USER_GUESS';r.status='ACTIVE'}if(action==='DELETED')r.status='DELETED';c.version+=1;save();showMemory();render()}
function wireChips(){document.querySelectorAll('[data-prompt]').forEach(btn=>btn.addEventListener('click',()=>{$('composer').value=btn.dataset.prompt;$('send').disabled=false;$('composer').focus()}))}
$('newConversation').addEventListener('click',createConversation);$('toggleSidebar').addEventListener('click',()=>{sidebarVisible=!sidebarVisible;$('app').classList.toggle('sidebar-hidden',!sidebarVisible)});$('composer').addEventListener('input',()=>{$('send').disabled=!$('composer').value.trim()});$('composer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if($('composer').value.trim())$('send').click()}});$('send').addEventListener('click',()=>{const value=$('composer').value.trim();if(!value)return;$('composer').value='';$('send').disabled=true;addRun(value)});
$('fileInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;if(!/\.(txt|md)$/i.test(f.name)||f.size>65536){showError('仅支持 64 KiB 以内的 TXT / Markdown');e.target.value='';return}try{const text=await f.text();addRun('已上传文件：'+f.name+'\n\n'+text.slice(0,1800),{fileName:f.name})}catch{showError('无法读取文本文件')}e.target.value=''});
$('openLab').addEventListener('click',()=>{const c=current();if(c?.runs.length)showLab(c.runs[c.runs.length-1].id)});$('openMemory').addEventListener('click',showMemory);$('closePanel').addEventListener('click',()=>$('panel').close());$('panel').addEventListener('cancel',e=>{e.preventDefault();$('panel').close()});$('resetPreview').addEventListener('click',()=>{if(confirm('清空这个浏览器中的 HCL Assistant Preview 数据？')){localStorage.removeItem(STORAGE_KEY);state.conversations=[];currentId=null;save();render()}});$('memoryScope').addEventListener('change',()=>{$('topicSelect').disabled=$('memoryScope').value==='TEMPORARY'});function showError(message){$('error').textContent=message;$('error').hidden=false;setTimeout(()=>{$('error').hidden=true},4000)}
render();
