import {InspectionView} from '../apps/web/src/InspectionView';
import {previewInspection} from './inspection';
import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AssistantShell} from '../apps/web/src/AssistantShell';
import {ProductDialog} from '../apps/web/src/ProductDialog';
import type {TurnView,AttachmentView} from '../apps/web/src/product-view';
import type {HistoryHit} from '../apps/web/src/history-view';
import {downloadJson} from '../apps/web/src/download';
import {STORAGE_KEY,LEGACY_KEY,emptyState,loadState,saveState,createConversation,submit,changeRecord,resolveBasis,decodeFile,reviseRecord,exportConversation} from './preview-model.js';
async function locked<T>(action:()=>T|Promise<T>):Promise<T>{if(!navigator.locks)return Promise.reject(new Error('此浏览器不支持安全多页面存储（Web Locks），未写入数据'));return await navigator.locks.request('hcl-assistant-preview-storage',action)}
function App(){
 const [state,setState]=useState(emptyState),data=useRef(state),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),writing=useRef(false),[error,setError]=useState(''),[text,setText]=useState(''),textRef=useRef(''),drafts=useRef(new Map<string,string>()),draftOrigins=useRef(new Map<string,string>()),input=useRef<HTMLTextAreaElement>(null),[memory,setMemory]=useState('CONVERSATION'),[attachment,setAttachment]=useState<AttachmentView|null>(null),attachmentOrigin=useRef<string|null>(null),[panel,setPanel]=useState<{kind:string;runId?:string;recordId?:string;returnKind?:string}|null>(null),[edit,setEdit]=useState<{id:string;intent:string;value:string}|null>(null),nav=useRef(0);
 function clearAttachment(){attachmentOrigin.current=null;setAttachment(null)}
 function publish(next:any){if(attachmentOrigin.current&&!next.conversations.some((c:any)=>c.records.some((r:any)=>r.id===attachmentOrigin.current&&r.status!=='DELETED'))){attachmentOrigin.current=null;clearAttachment()}for(const [id,runId] of draftOrigins.current){const c=next.conversations.find((c:any)=>c.id===id);if(!c?.runs.some((r:any)=>r.id===runId)){draftOrigins.current.delete(id);drafts.current.delete(id);if(next.currentId===id){textRef.current='';setText('')}}}data.current=next;setState(next)}
 function draft(value:string){if(!value)draftOrigins.current.delete(data.current.currentId||'new');textRef.current=value;setText(value);drafts.current.set(data.current.currentId||'new',value)}
 useEffect(()=>{let mounted=true;void locked(()=>loadState(localStorage)).then(value=>{if(mounted){publish(value);setReady(true)}}).catch(e=>setError('无法安全读取存储，未覆盖原数据：'+String(e)));
  const synchronize=(event:StorageEvent)=>{if(![STORAGE_KEY,LEGACY_KEY,null].includes(event.key))return;void locked(()=>{const latest=loadState(localStorage),temporary=data.current.conversations.filter((c:any)=>c.memory==='TEMPORARY'),current=data.current.currentId;const next={...latest,conversations:[...temporary,...latest.conversations]};next.currentId=next.conversations.some((c:any)=>c.id===current)?current:latest.currentId;publish(next);setPanel(null);setEdit(null)}).catch(e=>{publish(emptyState());setReady(false);setPanel(null);setEdit(null);setError('其他页面数据变更无法安全读取，请刷新：'+String(e))})};window.addEventListener('storage',synchronize);return()=>{mounted=false;window.removeEventListener('storage',synchronize)}},[]);
 async function commit(change:(next:any)=>any){if(!ready||writing.current){setError(ready?'正在保存，请稍后重试':'存储尚未可用，未写入数据');return null}writing.current=true;setBusy(true);setError('');try{return await locked(()=>{const next=JSON.parse(JSON.stringify(data.current));const result=change(next);saveState(next,localStorage);publish(next);return result||true})}catch(e){setError('操作未保存，原记录未改变：'+String(e));return null}finally{writing.current=false;setBusy(false)}}
 async function create(){const before=textRef.current,previous=data.current.currentId||'new';nav.current++;const c=await commit(next=>createConversation(next,memory));if(c){drafts.current.set(previous,before);if(textRef.current===before)draft('');else drafts.current.set(c.id,textRef.current);setPanel(null);setEdit(null);clearAttachment()}return c}
 function open(id:string){drafts.current.set(data.current.currentId||'new',textRef.current);nav.current++;publish({...data.current,currentId:id});draft(drafts.current.get(id)||'');setPanel(null);setEdit(null);clearAttachment();setError('')}
 async function send(){const original=textRef.current,value=original.trim(),target=data.current.currentId;if(!value)return;const result=await commit(next=>{let c=next.conversations.find((c:any)=>c.id===target);if(!c)c=createConversation(next,memory);return submit(next,c.id,value)});if(result&&textRef.current===original&&(!target||data.current.currentId===target))draft('')}
 async function upload(f:File,onAccepted?:()=>void){const target=data.current.currentId,token=nav.current;attachmentOrigin.current=null;setAttachment({name:f.name,status:'reading'});try{const parsed=decodeFile(f.name,new Uint8Array(await f.arrayBuffer()));if(token!==nav.current||target!==data.current.currentId)throw new Error('读取期间对话已切换，请重新选择文件');const result=await commit(next=>{let c=next.conversations.find((c:any)=>c.id===target);if(!c)c=createConversation(next,memory);return submit(next,c.id,parsed.content,parsed)});if(result)onAccepted?.();if(token!==nav.current)return {accepted:Boolean(result),conversationId:result?.conversationId||target};if(result){attachmentOrigin.current=result.recordId;setAttachment({name:f.name,status:'registered',detail:parsed.byteLength+' 字节'})}else setAttachment({name:f.name,status:'failed',detail:'未登记'});return {accepted:Boolean(result),conversationId:data.current.currentId}}catch(e){if(token===nav.current){setError(String(e));setAttachment({name:f.name,status:'failed',detail:String(e)})}return {accepted:false,conversationId:target}}}
 async function change(id:string,action:string){const result=await commit(next=>changeRecord(next,data.current.currentId,id,action));if(result)setEdit(null)}
 async function revise(){if(!edit)return;const result=await commit(next=>reviseRecord(next,data.current.currentId,edit.id,edit.intent,edit.value));if(result)setEdit(null)}
 function refreshed(){const latest=loadState(localStorage),current=data.current.currentId;const next={...latest,conversations:[...data.current.conversations.filter((c:any)=>c.memory==='TEMPORARY'),...latest.conversations]};next.currentId=next.conversations.some((c:any)=>c.id===current)?current:latest.currentId;publish(next);return next}
 async function search(query:string):Promise<HistoryHit[]>{return locked(()=>{const latest=refreshed(),hits:HistoryHit[]=[];for(const conv of latest.conversations){const changes=conv.runs.filter((r:any)=>r.revision&&r.revision.materialChanged!==false).map((r:any)=>({action:r.revision.type,old:resolveBasis(conv,r).filter((r:any)=>r.content).map((r:any)=>({content:r.content})),new:[...conv.records,...(conv.branches||[]).map((b:any)=>b.record)].filter((record:any)=>record.id===r.revision.newRecordId&&record.status!=='DELETED').map((record:any)=>({content:record.content}))}));for(const run of conv.runs){const body=run.input+'\n'+run.text,index=body.toLocaleLowerCase().indexOf(query.toLocaleLowerCase());if(index>=0)hits.push({conversation_id:conv.id,run_id:run.id,title:conv.title,snippet:body.slice(Math.max(0,index-40),index+query.length+100),historical:run.version!==conv.version,scope:conv.memory,related_changes:changes});if(hits.length>=50)return hits}}return hits})}
 async function exportCurrent(){try{await locked(()=>{const latest=refreshed(),c=latest.conversations.find((c:any)=>c.id===latest.currentId);if(c)downloadJson(exportConversation(c),`synthetic-conversation-${c.id}.json`)})}catch(e){setError(String(e))}}
 async function reset(){if(!confirm('清空这个浏览器中的合成预览数据？'))return false;try{await locked(()=>{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(LEGACY_KEY);publish(emptyState());drafts.current.clear();draftOrigins.current.clear();draft('');setPanel(null);setEdit(null);clearAttachment();setReady(true);setError('')});return true}catch(e){setError('重置失败：'+String(e));return false}}
 const c=state.conversations.find((row:any)=>row.id===state.currentId),found=panel?.runId?c?.runs.find((run:any)=>run.id===panel.runId):null;
 const allRecords=[...(c?.records||[]),...(c?.branches||[]).map((b:any)=>b.record)],sourceRecord=allRecords.find((r:any)=>r.id===panel?.recordId);
 const turns:TurnView[]=(c?.runs||[]).map((run:any)=>({id:run.id,input:run.input,file:c.records.find((r:any)=>r.id===run.recordId&&r.status==='ACTIVE'&&r.kind==='FILE')?{id:'source',label:c.records.find((r:any)=>r.id===run.recordId).fileName,onActivate:()=>setPanel({kind:'source',runId:run.id})}:undefined,output:(run.legacyUnverified?'[旧版未验证模板，不代表真实依据] ':'')+run.text,notice:run.status==='UNSUPPORTED'?run.uncertainty:undefined,change:run.revision&&run.revision.materialChanged!==false?{id:'change',label:'查看变化',onActivate:()=>setPanel({kind:'change',runId:run.id})}:undefined,evidence:{id:'evidence',label:'查看依据',onActivate:()=>setPanel({kind:'evidence',runId:run.id})},actions:[{id:'source',label:'查看输入原文',onActivate:()=>setPanel({kind:'source',runId:run.id})},{id:'inspect',label:'在 Lab 检查',onActivate:()=>setPanel({kind:'lab',runId:run.id})}]}));
 const panelTitle=panel?.kind==='memory'?'记忆管理':panel?.kind==='evidence'?'查看依据':['source','record-source'].includes(panel?.kind||'')?'原文':panel?.kind==='change'?'理解变化':'HCL Lab';
 return <AssistantShell contextActive={Boolean(panel&&['evidence','source','record-source','change'].includes(panel.kind))} contextKind={panel?.kind.includes('source')?'source':panel?.kind==='change'?'revision':'evidence'} inputRef={input} environment="交互演示，不连接模型" environmentDetails={<><p>Pages browser-only：未接入真实 HCL、API/backend或provider。所有输入只走明确的synthetic Controller。</p><p>临时正文留在页面内存，刷新或重开即消失；其他会话保存在此浏览器localStorage。只使用合成信息，Provider calls:0。</p><p>精确演示：2+2；记录：合成背景；演示：查看当前背景；更正 record-ID：新内容。开放问题暂不支持。</p></>}
  conversations={state.conversations} currentId={state.currentId} title={c?.title||'新对话'} scope={c?.memory==='TEMPORARY'?'临时 · 刷新即消失':c?.topic?'本会话背景 · 旧项目标签不复用':'本会话背景'} turns={turns} draft={text} setDraft={draft} onEdit={(id,value)=>{draft(value);draftOrigins.current.set(data.current.currentId,id)}} busy={busy||!ready} error={error} attachment={attachment} onNew={create} onOpen={open} onSend={send} onUpload={upload} onMemory={()=>setPanel({kind:'memory'})} onSearch={search} historyRevision={state.storageRevision+':'+(c?.version||0)} onExport={exportCurrent} onReset={reset} onInspect={c?.runs.length?()=>setPanel({kind:'lab',runId:c.runs[c.runs.length-1].id}):undefined}
  settings={<><label>记忆范围<select id="memoryScope" aria-label="记忆范围" value={memory} onChange={e=>setMemory(e.target.value)}><option value="CONVERSATION">仅会话 · 此浏览器保存</option><option value="TEMPORARY">临时 · 刷新消失</option></select></label><p>此静态演示不支持项目内跨会话背景复用。</p></>}
  panels={panel&&<ProductDialog label={panelTitle} onClose={()=>{setPanel(null);setEdit(null)}}>
   {panel.kind==='memory'&&<><h2>可管理的背景</h2><p>停止使用阻止后续选择；删除清理关联原文、回答和缓存。独立来源不会随之删除。历史与背景是不同对象。</p>{(c?.records||[]).map((r:any)=><section className="memory-row memory-card" key={r.id}><small>{r.fileName?r.fileName+' · ':''}{r.kind} · {r.status} · v{r.version}</small><p>{r.content||'正文已删除'}</p><details><summary>记录与来源</summary><small>{r.id}</small>{r.status!=='DELETED'&&<button onClick={()=>setPanel({kind:'record-source',recordId:r.id,returnKind:'memory'})}>查看原文</button>}</details>{r.status==='ACTIVE'&&<><button disabled={busy} onClick={()=>void change(r.id,'STOPPED')}>停止使用</button>{r.kind!=='UNRESOLVED'&&!r.legacy&&<><button disabled={busy} onClick={()=>void change(r.id,'GUESS')}>这只是猜测</button>{[['CORRECT','内容不对'],['SUPERSEDE','从现在变化'],['HYPOTHETICAL_BRANCH','假设另一种情况']].map(([intent,label])=><button key={intent} disabled={busy} onClick={()=>setEdit({id:r.id,intent,value:r.content})}>{label}</button>)}</>}</>}{r.status!=='DELETED'&&<button disabled={busy} className="danger" onClick={()=>void change(r.id,'DELETED')}>删除</button>}</section>)}{(c?.branches||[]).map((b:any)=><section className="memory-row memory-card" key={b.id}><small>隔离假设 · 不用于实际背景</small><p>{b.record.content}</p><button disabled={busy} onClick={()=>void change(b.record.id,'DELETED')}>删除假设</button></section>)}{edit&&<form onSubmit={e=>{e.preventDefault();void revise()}}><h3>{edit.intent==='SUPERSEDE'?'从现在变化':edit.intent==='HYPOTHETICAL_BRANCH'?'假设另一种情况':'更正旧信息'}</h3><p>{edit.intent==='HYPOTHETICAL_BRANCH'?'假设不会写回实际背景':edit.intent==='SUPERSEDE'?'从提交起生效，不倒填事件或人物获知时间':'只修改明确选定记录；旧回答不改写'}</p><label>新内容<input autoFocus aria-label="修订值" value={edit.value} onChange={e=>setEdit({...edit,value:e.target.value})}/></label><button disabled={busy||!edit.value.trim()}>提交更正并更新回答</button><button type="button" onClick={()=>setEdit(null)}>取消更正</button></form>}</>}
   {panel.kind==='evidence'&&found&&<><h2>当次回答依据</h2><p>仅投影实际选取的记录，零模型调用，不是隐藏思维。</p>{resolveBasis(c,found).length?resolveBasis(c,found).map(ref=><section key={ref.recordId}><small>{ref.kind} · {ref.classificationStatus} · {ref.status}</small><p>{ref.content||'原文不可用'}</p>{ref.content&&<button data-source={ref.recordId} onClick={()=>setPanel({kind:'record-source',recordId:ref.recordId,runId:found.id,returnKind:'evidence'})}>查看来源 v{ref.version}</button>}</section>):<p>本次没有人物背景依据。</p>}<p>{found.uncertainty}</p>{found.change&&<p>{found.change}</p>}<button onClick={()=>{setEdit(null);setPanel({kind:'memory'})}}>纠正或管理背景</button></>}
   {panel.kind==='source'&&found&&<><h2>当时的输入原文</h2><pre>{found.input}</pre><p>登记不代表语义理解</p></>}
   {panel.kind==='record-source'&&<><button className="source-return" onClick={()=>{const id=panel.recordId;setPanel({kind:panel.returnKind||'memory',runId:panel.runId});if(id)requestAnimationFrame(()=>document.querySelector<HTMLElement>('[data-source="'+CSS.escape(id)+'"]')?.focus({preventScroll:true}))}}>{panel.returnKind==='evidence'?'返回依据':'返回记忆'}</button><h2>当时登记的原文</h2>{sourceRecord&&sourceRecord.status!=='DELETED'?<><small>版本{sourceRecord.version} · {sourceRecord.status}</small><pre>{sourceRecord.content}</pre></>:<p>原文已删除或不可访问</p>}<p>来源定位不证明语义支持；假设不会写回实际背景。</p></>}
   {panel.kind==='change'&&found?.revision&&<><h2>{found.revision.type==='GUESS'?'降回猜测':found.revision.type==='SUPERSEDE'?'从现在变化':found.revision.type==='HYPOTHETICAL_BRANCH'?'隔离假设':'更正旧信息'}</h2><div className="change-columns"><section><strong>旧依据</strong>{resolveBasis(c,found).map(ref=><p key={ref.recordId}>{ref.kind}：{ref.content||'当前不可用'}</p>)}</section><section><strong>新信息</strong><p>{allRecords.find((r:any)=>r.id===found.revision.newRecordId)?.content||'当前不可用'}</p></section></div><p>{found.change}</p><p>未重新评估：{found.revision.notReevaluatedRunIds?.length||0}；没有自动证明替代解释。事件时间与人物获知时间：未知。</p>{found.revision.effectiveTime&&<p>从本次提交起生效：{found.revision.effectiveTime}</p>}<button onClick={()=>setPanel({kind:'evidence',runId:found.id})}>查看依据</button></>}
   {panel.kind==='lab'&&found&&<InspectionView value={previewInspection(c,found)}/>}
  </ProductDialog>}/>
}
createRoot(document.getElementById('root')!).render(<App/>);
