import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AssistantShell} from '../apps/web/src/AssistantShell';
import {ProductDialog} from '../apps/web/src/ProductDialog';
import type {TurnView,AttachmentView} from '../apps/web/src/product-view';
import {STORAGE_KEY,LEGACY_KEY,emptyState,loadState,saveState,createConversation,submit,changeRecord,resolveBasis,decodeFile} from './preview-model.js';
async function locked<T>(action:()=>T|Promise<T>):Promise<T>{if(!navigator.locks)return Promise.reject(new Error('此浏览器不支持安全多页面存储（Web Locks），未写入数据'));return await navigator.locks.request('hcl-assistant-preview-storage',action)}
function App(){
 const [state,setState]=useState(emptyState),data=useRef(state),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),writing=useRef(false),[error,setError]=useState(''),[text,setText]=useState(''),textRef=useRef(''),drafts=useRef(new Map<string,string>()),draftOrigins=useRef(new Map<string,string>()),input=useRef<HTMLTextAreaElement>(null),[memory,setMemory]=useState('CONVERSATION'),[attachment,setAttachment]=useState<AttachmentView|null>(null),[panel,setPanel]=useState<{kind:string;runId?:string}|null>(null),nav=useRef(0);
 function publish(next:any){for(const [id,runId] of draftOrigins.current){const c=next.conversations.find((c:any)=>c.id===id);if(!c?.runs.some((r:any)=>r.id===runId)){draftOrigins.current.delete(id);drafts.current.delete(id);if(next.currentId===id){textRef.current='';setText('')}}}data.current=next;setState(next)}
 function draft(value:string){if(!value)draftOrigins.current.delete(data.current.currentId||'new');textRef.current=value;setText(value);drafts.current.set(data.current.currentId||'new',value)}
 useEffect(()=>{let mounted=true;void locked(()=>loadState(localStorage)).then(value=>{if(mounted){publish(value);setReady(true)}}).catch(e=>setError('无法安全读取存储，未覆盖原数据：'+String(e)));
  const synchronize=(event:StorageEvent)=>{if(![STORAGE_KEY,LEGACY_KEY,null].includes(event.key))return;void locked(()=>{const latest=loadState(localStorage),temporary=data.current.conversations.filter((c:any)=>c.memory==='TEMPORARY'),current=data.current.currentId;const next={...latest,conversations:[...temporary,...latest.conversations]};next.currentId=next.conversations.some((c:any)=>c.id===current)?current:latest.currentId;publish(next);setPanel(null)}).catch(e=>{publish(emptyState());setReady(false);setPanel(null);setError('其他页面数据变更无法安全读取，请刷新：'+String(e))})};window.addEventListener('storage',synchronize);return()=>{mounted=false;window.removeEventListener('storage',synchronize)}},[]);
 async function commit(change:(next:any)=>any){if(!ready||writing.current){setError(ready?'正在保存，请稍后重试':'存储尚未可用，未写入数据');return null}writing.current=true;setBusy(true);setError('');try{return await locked(()=>{const next=JSON.parse(JSON.stringify(data.current));const result=change(next);saveState(next,localStorage);publish(next);return result||true})}catch(e){setError('操作未保存，原记录未改变：'+String(e));return null}finally{writing.current=false;setBusy(false)}}
 async function create(){const before=textRef.current,previous=data.current.currentId||'new';nav.current++;const c=await commit(next=>createConversation(next,memory));if(c){drafts.current.set(previous,before);if(textRef.current===before)draft('');else drafts.current.set(c.id,textRef.current);setPanel(null);setAttachment(null)}return c}
 function open(id:string){drafts.current.set(data.current.currentId||'new',textRef.current);nav.current++;publish({...data.current,currentId:id});draft(drafts.current.get(id)||'');setPanel(null);setAttachment(null);setError('')}
 async function send(){const original=textRef.current,value=original.trim(),target=data.current.currentId;if(!value)return;const result=await commit(next=>{let c=next.conversations.find((c:any)=>c.id===target);if(!c)c=createConversation(next,memory);return submit(next,c.id,value)});if(result&&textRef.current===original&&(!target||data.current.currentId===target))draft('')}
 async function upload(f:File){const target=data.current.currentId,token=nav.current;setAttachment({name:f.name,status:'reading'});try{const parsed=decodeFile(f.name,new Uint8Array(await f.arrayBuffer()));if(token!==nav.current||target!==data.current.currentId)throw new Error('读取期间对话已切换，请重新选择文件');const result=await commit(next=>{let c=next.conversations.find((c:any)=>c.id===target);if(!c)c=createConversation(next,memory);return submit(next,c.id,parsed.content,parsed)});if(token!==nav.current)return;if(result)setAttachment({name:f.name,status:'registered',detail:parsed.byteLength+' 字节'});else setAttachment({name:f.name,status:'failed',detail:'未登记'})}catch(e){setError(String(e));setAttachment({name:f.name,status:'failed',detail:String(e)})}}
 async function change(id:string,action:string){await commit(next=>changeRecord(next,data.current.currentId,id,action))}
 async function reset(){if(!confirm('清空这个浏览器中的合成预览数据？'))return;try{await locked(()=>{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(LEGACY_KEY);publish(emptyState());drafts.current.clear();draftOrigins.current.clear();draft('');setPanel(null);setAttachment(null);setReady(true);setError('')})}catch(e){setError('重置失败：'+String(e))}}
 const c=state.conversations.find((row:any)=>row.id===state.currentId),found=panel?.runId?c?.runs.find((run:any)=>run.id===panel.runId):null;
 const turns:TurnView[]=(c?.runs||[]).map((run:any)=>({id:run.id,input:run.input,output:(run.legacyUnverified?'[旧版未验证模板，不代表真实依据] ':'')+run.text,notice:run.status==='UNSUPPORTED'?run.uncertainty:undefined,evidence:{id:'evidence',label:'查看依据',onActivate:()=>setPanel({kind:'evidence',runId:run.id})},actions:[{id:'source',label:'查看输入原文',onActivate:()=>setPanel({kind:'source',runId:run.id})},{id:'inspect',label:'在 Lab 检查',onActivate:()=>setPanel({kind:'lab',runId:run.id})}]}));
 const panelTitle=panel?.kind==='memory'?'记忆管理':panel?.kind==='evidence'?'查看依据':panel?.kind==='source'?'原文':'HCL Lab';
 return <AssistantShell inputRef={input} environment="交互演示，不连接模型" environmentDetails={<><p>Pages browser-only：未接入真实 HCL、API/backend或provider。所有输入只走明确的synthetic Controller。</p><p>临时正文留在页面内存，刷新或重开即消失；其他会话保存在此浏览器localStorage。只使用合成信息，Provider calls:0。</p><p>精确演示：2+2；记录：合成背景；演示：查看当前背景；更正 record-ID：新内容。开放问题暂不支持。</p></>}
  conversations={state.conversations} currentId={state.currentId} title={c?.title||'新对话'} scope={c?.memory==='TEMPORARY'?'临时 · 刷新即消失':c?.topic?'本会话背景 · 旧项目标签不复用':'本会话背景'} turns={turns} draft={text} setDraft={draft} onEdit={(id,value)=>{draft(value);draftOrigins.current.set(data.current.currentId,id)}} busy={busy||!ready} error={error} attachment={attachment} onNew={create} onOpen={open} onSend={send} onUpload={upload} onMemory={()=>setPanel({kind:'memory'})} onReset={reset} onInspect={c?.runs.length?()=>setPanel({kind:'lab',runId:c.runs[c.runs.length-1].id}):undefined}
  settings={<><label>记忆范围<select id="memoryScope" aria-label="记忆范围" value={memory} onChange={e=>setMemory(e.target.value)}><option value="CONVERSATION">仅会话 · 此浏览器保存</option><option value="TEMPORARY">临时 · 刷新消失</option></select></label><p>此静态演示不支持项目内跨会话背景复用。</p></>}
  panels={panel&&<ProductDialog label={panelTitle} onClose={()=>setPanel(null)}>
   {panel.kind==='memory'&&<><h2>可管理的背景</h2><p>停止使用阻止后续选择；删除清理关联原文、回答和缓存。独立来源不会随之删除。</p>{(c?.records||[]).map((r:any)=><section className="memory-row memory-card" key={r.id}><small>{r.id} · {r.kind} · {r.status} · v{r.version}</small><p>{r.content||'正文已删除'}</p>{r.status==='ACTIVE'&&<><button disabled={busy} onClick={()=>void change(r.id,'STOPPED')}>停止使用</button><button disabled={busy} onClick={()=>void change(r.id,'GUESS')}>这只是猜测</button></>}{r.status!=='DELETED'&&<button disabled={busy} className="danger" onClick={()=>void change(r.id,'DELETED')}>删除</button>}</section>)}</>}
   {panel.kind==='evidence'&&found&&<><h2>当次回答依据</h2><p>仅投影实际选取的记录，零模型调用，不是隐藏思维。</p>{resolveBasis(c,found).length?resolveBasis(c,found).map(ref=><section key={ref.recordId}><small>{ref.recordId} · {ref.status}</small><p>{ref.content||'原文不可用'}</p></section>):<p>本次没有人物背景依据。</p>}<p>{found.uncertainty}</p>{found.change&&<p>{found.change}</p>}</>}
   {panel.kind==='source'&&found&&<><h2>当时的输入原文</h2><pre>{found.input}</pre><p>登记不代表语义理解</p></>}
   {panel.kind==='lab'&&found&&<><h2>只读静态演示记录</h2><p>未接入真实 HCL；成功运行不代表效力。Provider calls:0。</p><dl><dt>Route</dt><dd>{found.route}</dd><dt>状态</dt><dd>{found.status||'LEGACY_UNVERIFIED'}</dd><dt>版本</dt><dd>{found.version}</dd></dl><pre>{JSON.stringify({basis:resolveBasis(c,found),capabilities:found.caps,uncertainty:found.uncertainty},null,2)}</pre><p>Compare尚未获准，不执行或伪造比较。</p></>}
  </ProductDialog>}/>
}
createRoot(document.getElementById('root')!).render(<App/>);
