import React,{useEffect,useRef,useState} from 'react';
import {Markdown} from './Markdown';
import {ProductDialog} from './ProductDialog';
import type {ConversationView,TurnView,AttachmentView} from './product-view';
import './style.css';
type Props={environment:string;environmentDetails:React.ReactNode;conversations:ConversationView[];currentId:string|null;title:string;scope:string;turns:TurnView[];draft:string;setDraft:(text:string)=>void;busy:boolean;error:string;attachment?:AttachmentView|null;onNew:()=>void|Promise<unknown>;onOpen:(id:string)=>void|Promise<unknown>;onSend:()=>void|Promise<unknown>;onUpload:(file:File)=>void|Promise<unknown>;onStop?:()=>void|Promise<unknown>;onMemory:()=>void;settings:React.ReactNode;onInspect?:()=>void;onReset?:()=>void|Promise<unknown>;panels?:React.ReactNode;inputRef?:React.RefObject<HTMLTextAreaElement|null>};
export function AssistantShell(p:Props){
 const [sidebar,setSidebar]=useState(()=>innerWidth>=960),[settings,setSettings]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[environment,setEnvironment]=useState(false),[copyError,setCopyError]=useState('');
 const ownInput=useRef<HTMLTextAreaElement>(null),input=p.inputRef||ownInput,scroll=useRef<HTMLDivElement>(null),bottom=useRef(true),toggle=useRef<HTMLButtonElement>(null),file=useRef<HTMLInputElement>(null),composing=useRef(false),lastConversation=useRef(p.currentId);
 useEffect(()=>{const el=input.current;if(el){el.style.height='auto';el.style.height=Math.min(208,Math.max(52,el.scrollHeight))+'px'}},[p.draft]);
 useEffect(()=>{if(lastConversation.current!==p.currentId){bottom.current=true;lastConversation.current=p.currentId}if(bottom.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight},[p.currentId,p.turns]);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&sidebar&&innerWidth<960){setSidebar(false);toggle.current?.focus()}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[sidebar]);
 async function create(){await p.onNew();if(innerWidth<960)setSidebar(false);input.current?.focus()}
 async function open(id:string){await p.onOpen(id);if(innerWidth<960)setSidebar(false);setSearch(false);input.current?.focus()}
 const history=p.conversations.filter(c=>!query||c.title.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <div className={'layout'+(sidebar?'':' collapsed')}>
  {sidebar&&<><button className="nav-scrim" aria-label="关闭侧栏" onClick={()=>{setSidebar(false);toggle.current?.focus()}}/><aside id="sidebar"><div className="brand">HCL <span>Assistant</span></div><button id="newConversation" className="new-conversation" onClick={()=>void create()}>＋ 新对话</button><button onClick={()=>{setQuery('');setSearch(true)}}>搜索对话</button><nav aria-label="对话历史">{p.conversations.length===0?<p className="muted">还没有对话</p>:p.conversations.map(c=><button key={c.id} aria-current={p.currentId===c.id} onClick={()=>void open(c.id)}><span>{c.title}</span>{c.memory==='TEMPORARY'&&<small>临时</small>}</button>)}</nav><div className="sidebar-bottom"><button id="openMemory" disabled={!p.currentId} onClick={p.onMemory}>记忆管理</button><button onClick={()=>setSettings(true)}>设置</button></div></aside></>}
  <section className="chat-workspace"><header><button ref={toggle} aria-label="切换侧栏" aria-controls="sidebar" aria-expanded={sidebar} onClick={()=>setSidebar(!sidebar)}>☰</button><div className="conversation-identity"><strong>{p.title}</strong><span aria-label="当前对话范围">{p.scope}</span></div><button className="environment" onClick={()=>setEnvironment(true)}>{p.environment}</button></header>
  <main><div ref={scroll} className="messages" aria-label="消息记录" aria-live="polite" onScroll={()=>{const el=scroll.current;if(el)bottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<80}}>{p.turns.length===0?<section className="empty"><h1>有什么需要帮忙的？</h1><p>可以补充资料，也可以更正已经记录的信息</p><p className="muted">当前为合成交互演示，开放问题不会获得真实模型回答</p></section>:p.turns.map(turn=><article key={turn.id} data-run={turn.id}>{turn.input&&<div className="user-message">{turn.input}</div>}<div className="assistant-message"><Markdown text={turn.output}/>{turn.notice&&<p className="turn-notice">{turn.notice}</p>}{turn.pending&&<p role="status">正在接收结果，可随时停止</p>}</div><div className="turn-actions">{turn.evidence&&<button onClick={turn.evidence.onActivate}>{turn.evidence.label}</button>}{turn.sources?.map(a=><button key={a.id} onClick={a.onActivate}>{a.label}</button>)}{turn.retry&&<button disabled={turn.retry.disabled} onClick={turn.retry.onActivate}>{turn.retry.label}</button>}<details><summary aria-label="更多消息操作">更多</summary><div className="message-menu"><button onClick={()=>void navigator.clipboard.writeText(turn.output).catch(()=>setCopyError('复制失败，请手动选择文本'))}>复制回答</button>{turn.input&&<button onClick={()=>{p.setDraft(turn.input!);input.current?.focus()}}>编辑为新消息</button>}{turn.actions.map(a=><button key={a.id} disabled={a.disabled} onClick={a.onActivate}>{a.label}</button>)}</div></details></div></article>)}</div>
  {(p.error||copyError)&&<p role="alert" className="error">{p.error||copyError}</p>}
  <form className="composer" onSubmit={e=>{e.preventDefault();if(!p.busy&&p.draft.trim())void p.onSend()}}><textarea ref={input} id="composer" aria-label="消息" placeholder="输入问题或想法" value={p.draft} onChange={e=>p.setDraft(e.target.value)} onCompositionStart={()=>composing.current=true} onCompositionEnd={()=>composing.current=false} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&!composing.current&&e.nativeEvent.keyCode!==229){e.preventDefault();if(!p.busy&&p.draft.trim())void p.onSend()}}}/>{p.attachment&&<div className="attachment" role="status">{p.attachment.name} · {p.attachment.status==='reading'?'读取中':p.attachment.status==='registered'?'已完整登记，未声明语义理解':'读取失败'}{p.attachment.detail&&' · '+p.attachment.detail}</div>}<div className="composer-controls"><input ref={file} type="file" id="fileInput" className="file-input" accept=".txt,.md" aria-label="上传文本文件" disabled={p.busy} onChange={e=>{const selected=e.target.files?.[0];if(selected)void p.onUpload(selected);e.target.value=''}}/><button type="button" disabled={p.busy} aria-label="附加文本资料" onClick={()=>file.current?.click()}>＋ 附加资料</button><small>TXT / Markdown · 64 KiB · 仅合成资料</small>{p.busy&&p.onStop?<button type="button" onClick={()=>void p.onStop!()}>停止</button>:<button id="send" className="send" disabled={p.busy||!p.draft.trim()} type="submit">{p.busy?'保存中':'发送'}</button>}</div></form><p className="composer-note">演示记录不代表模型理解；请勿输入真实私密信息</p></main></section>
  {settings&&<ProductDialog label="设置" onClose={()=>setSettings(false)}><h2>下一次新建对话</h2><p>这些选项只用于下一次新建，不更改当前对话的范围</p>{p.settings}<details><summary>高级与演示</summary><div>{p.environmentDetails}</div>{p.onInspect&&<button onClick={()=>{setSettings(false);p.onInspect!()}}>HCL Lab</button>}{p.onReset&&<button className="danger" onClick={()=>void p.onReset!()}>重置合成预览</button>}</details></ProductDialog>}
  {environment&&<ProductDialog label="演示环境" onClose={()=>setEnvironment(false)}><h2>{p.environment}</h2>{p.environmentDetails}</ProductDialog>}
  {search&&<ProductDialog label="搜索对话" onClose={()=>setSearch(false)}><label>按标题查找<input autoFocus value={query} onChange={e=>setQuery(e.target.value)}/></label><p className="muted">此处按对话标题查找；正文与背景检索在后续闭环提供</p><nav>{history.map(c=><button key={c.id} onClick={()=>void open(c.id)}>{c.title}</button>)}</nav>{history.length===0&&<p>没有匹配的对话</p>}</ProductDialog>}
  {p.panels}
 </div>
}
