import React,{useEffect,useRef,useState} from 'react';
import {Markdown} from './Markdown';
import {ProductDialog} from './ProductDialog';
import type {HistoryHit} from './history-view';
import type {ConversationView,TurnView,AttachmentView} from './product-view';
import './style.css';
import './continuum.css';
import {Companion} from './Companion';
import {ReadingAnchorContext,useReadingAnchor} from './ReadingAnchor';
type Props={contextActive?:boolean;contextKind?:string;live?:boolean;environment:string;environmentDetails:React.ReactNode;conversations:ConversationView[];currentId:string|null;title:string;scope:string;turns:TurnView[];draft:string;setDraft:(text:string)=>void;onEdit?:(turnId:string,text:string)=>void;busy:boolean;error:string;attachment?:AttachmentView|null;onNew:()=>void|Promise<unknown>;onOpen:(id:string)=>void|Promise<unknown>;onSend:()=>void|Promise<unknown>;onUpload:(file:File)=>void|Promise<unknown>;onStop?:()=>void|Promise<unknown>;onMemory:()=>void;onSearch?:(query:string)=>Promise<HistoryHit[]>;historyRevision?:string|number;onExport?:()=>void|Promise<unknown>;currentSettings?:React.ReactNode;settings:React.ReactNode;onInspect?:()=>void;onReset?:()=>void|Promise<unknown>;panels?:React.ReactNode;inputRef?:React.RefObject<HTMLTextAreaElement|null>};
export function AssistantShell(p:Props){
 const [sidebar,setSidebar]=useState(()=>innerWidth>=960),[settings,setSettings]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[environment,setEnvironment]=useState(false),[copyError,setCopyError]=useState('');
 const [companion,setCompanion]=useState<'orb'|'receiver'|'off'>('orb'),[motion,setMotion]=useState('auto'),[transparency,setTransparency]=useState('auto'),[unread,setUnread]=useState(false),[staged,setStaged]=useState<Record<string,File>>({}),[fileWorking,setFileWorking]=useState(false),[stageError,setStageError]=useState('');
 const stageKey=p.currentId||'new',stagedFile=staged[stageKey],activeStage=useRef(stageKey);activeStage.current=stageKey;
 const [hits,setHits]=useState<HistoryHit[]>([]),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(''),[hitRevision,setHitRevision]=useState(p.historyRevision);
 useEffect(()=>{let current=true;setHits([]);setHitRevision(p.historyRevision);setSearchError('');if(search&&query.trim()&&p.onSearch){setSearching(true);void p.onSearch(query).then(result=>{if(current){setHits(result);setHitRevision(p.historyRevision)}}).catch(e=>{if(current)setSearchError(String(e))}).finally(()=>{if(current)setSearching(false)})}else setSearching(false);return()=>{current=false}},[query,search,p.historyRevision]);
 const ownInput=useRef<HTMLTextAreaElement>(null),input=p.inputRef||ownInput,scroll=useRef<HTMLDivElement>(null),bottom=useRef(true),toggle=useRef<HTMLButtonElement>(null),file=useRef<HTMLInputElement>(null),composing=useRef(false),lastConversation=useRef(p.currentId);
 const reading=useReadingAnchor(scroll,p.currentId,Boolean(p.contextActive));
 useEffect(()=>{if(p.contextActive&&innerWidth<1280)setSidebar(false)},[p.contextActive]);
 useEffect(()=>{const el=input.current;if(el){el.style.height='auto';el.style.height=Math.min(208,Math.max(52,el.scrollHeight))+'px'}},[p.draft]);
 useEffect(()=>{if(lastConversation.current!==p.currentId){bottom.current=true;lastConversation.current=p.currentId}if(bottom.current&&!p.contextActive&&scroll.current){scroll.current.scrollTop=scroll.current.scrollHeight;setUnread(false)}else if(p.turns.length)setUnread(true)},[p.currentId,p.turns]);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&sidebar&&innerWidth<960){setSidebar(false);toggle.current?.focus()}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[sidebar]);
 useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setQuery('');setSearch(true)}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut)},[]);
 async function reset(){const result=await p.onReset?.();if(result===true){setStaged({});setStageError('')}}
 async function create(){await p.onNew();if(innerWidth<960)setSidebar(false);input.current?.focus()}
 async function open(id:string){await p.onOpen(id);if(innerWidth<960)setSidebar(false);setSearch(false);input.current?.focus()}
 function activate(action:TurnView['actions'][number],event:React.MouseEvent<HTMLButtonElement>){if(['source','evidence','change'].includes(action.id)||action.id.startsWith('source')){reading.capture(event.currentTarget);bottom.current=false}action.onActivate(event)}
 function stageFile(file:File){setStageError('');if(!/\.(txt|md)$/i.test(file.name)){setStageError('仅支持 TXT / Markdown');return}if(file.size>65536){setStageError('文件限制 64 KiB');return}setStaged(old=>({...old,[stageKey]:file}))}
 async function submitFile(){const file=staged[stageKey],key=stageKey;if(!file||fileWorking||p.busy)return;setFileWorking(true);setStageError('');try{const result=await p.onUpload(file) as {accepted?:boolean;conversationId?:string}|boolean|undefined;const accepted=result===true||(typeof result==='object'&&result?.accepted===true),target=typeof result==='object'?result?.conversationId:undefined;setStaged(old=>{if(old[key]!==file)return old;const next={...old};if(accepted)delete next[key];else if(target&&target!==key&&!next[target]){delete next[key];next[target]=file}return next})}catch{if(activeStage.current===key)setStageError('附件未提交，文件仍待提交，请检查错误后重试')}finally{setFileWorking(false)}}
 const history=p.conversations.filter(c=>!query||c.title.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <ReadingAnchorContext.Provider value={reading}><div className={'layout continuum-shell'+(sidebar?'':' collapsed')+(p.turns.length?'':' is-home')+(p.contextActive?' has-context':'')} data-context-kind={p.contextKind||''} data-motion={motion} data-transparency={transparency}>
  {sidebar&&<><button className="nav-scrim" aria-label="关闭侧栏" onClick={()=>{setSidebar(false);toggle.current?.focus()}}/><aside id="sidebar"><div className="brand">HCL <span>Assistant</span></div><button id="newConversation" className="new-conversation" onClick={()=>void create()}>＋ 新对话</button><button onClick={()=>{setQuery('');setSearch(true)}}>搜索对话</button><nav aria-label="对话历史">{p.conversations.length===0?<p className="muted">还没有对话</p>:p.conversations.map(c=><button data-conversation={c.id} key={c.id} aria-current={p.currentId===c.id} onClick={()=>void open(c.id)}><span>{c.title}</span>{c.memory==='TEMPORARY'&&<small>临时</small>}</button>)}</nav><div className="sidebar-bottom"><button id="openMemory" disabled={!p.currentId} onClick={p.onMemory}>记忆管理</button><button onClick={()=>setSettings(true)}>设置</button></div></aside></>}
  <section className="chat-workspace" data-current-conversation={p.currentId||''}><header><button ref={toggle} aria-label="切换侧栏" aria-controls="sidebar" aria-expanded={sidebar} onClick={()=>setSidebar(!sidebar)}>☰</button><div className="conversation-identity"><strong>{p.title}</strong><span aria-label="当前对话范围">{p.scope}</span></div><button className="header-search" onClick={()=>{setQuery('');setSearch(true)}} aria-label="搜索对话与文件"><span aria-hidden="true">⌕</span><span>搜索对话或已登记资料</span><kbd>⌘ K</kbd></button><button className="environment" onClick={()=>setEnvironment(true)}>{p.environment}</button></header>
  <main><div ref={scroll} className="messages" aria-label="消息记录" aria-live="polite" onWheel={reading.onIntent} onTouchStart={reading.onIntent} onPointerDown={event=>{if(event.target===scroll.current)reading.onIntent()}} onKeyDown={e=>{if(['PageUp','PageDown','ArrowUp','ArrowDown','Home','End'].includes(e.key))reading.onIntent()}} onScroll={()=>{const el=scroll.current;if(el){bottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;if(bottom.current)setUnread(false)}reading.onScroll()}}>{p.turns.length===0?<section className="empty home-stage"><div className="home-copy"><small>HCL Assistant</small><p className="home-greeting">你好，</p><h1>有什么需要<span>帮忙的？</span></h1><p>把想法、资料和问题放在这里，一起理清下一步。</p><p className="muted">{p.live?'开发态真实模型聊天；只使用原创合成输入':'当前为合成交互演示，开放问题不会获得真实模型回答'}</p></div>{companion!=='off'&&<div className="home-companion"><Companion variant={companion} size="home" busy={p.busy}/></div>}</section>:p.turns.map(turn=><article className={p.contextActive&&reading.selectedRun===turn.id?'is-context-target':undefined} key={turn.id} data-run={turn.id} tabIndex={-1}>{(turn.input||turn.file)&&<div className="user-message">{turn.file?<button className="file-reference" data-reading-anchor={turn.id+':file'} onClick={event=>activate(turn.file!,event)}><span aria-hidden="true">▤</span><span>{turn.file.label}</span><small>已登记资料 · 查看原文</small></button>:turn.input}</div>}<div className="assistant-message"><div className="answer-identity">{companion!=='off'&&<Companion variant={companion} size="mini" busy={Boolean(turn.pending)}/>}<span>HCL Assistant</span><small>{turn.pending?'正在接收结果':'当次回答'}</small></div><Markdown text={turn.output}/>{turn.notice&&<p className="turn-notice">{turn.notice}</p>}{turn.pending&&<p role="status">正在接收结果，可随时停止</p>}</div><div className="turn-actions">{turn.change&&<button data-reading-anchor={turn.id+':change'} onClick={event=>activate(turn.change!,event)}>{turn.change.label}</button>}{turn.evidence&&<button data-reading-anchor={turn.id+':evidence'} onClick={event=>activate(turn.evidence!,event)}>{turn.evidence.label}</button>}{turn.sources?.map(a=><button data-reading-anchor={turn.id+':source:'+a.id} key={a.id} onClick={event=>{reading.capture(event.currentTarget);bottom.current=false;a.onActivate(event)}}>{a.label}</button>)}{turn.retry&&<button disabled={turn.retry.disabled} onClick={turn.retry.onActivate}>{turn.retry.label}</button>}<details><summary aria-label="更多消息操作">更多</summary><div className="message-menu"><button onClick={()=>void navigator.clipboard.writeText(turn.output).catch(()=>setCopyError('复制失败，请手动选择文本'))}>复制回答</button>{turn.input&&<button onClick={()=>{if(p.onEdit)p.onEdit(turn.id,turn.input!);else p.setDraft(turn.input!);input.current?.focus()}}>编辑为新消息</button>}{turn.actions.map(a=><button data-reading-anchor={turn.id+':'+a.id} key={a.id} disabled={a.disabled} onClick={event=>activate(a,event)}>{a.label}</button>)}</div></details></div></article>)}</div>
  {unread&&<button className="new-content" onClick={()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;bottom.current=true;setUnread(false)}}>有新内容 · 回到底部</button>}{(p.error||stageError||copyError)&&<p role="alert" className="error">{p.error||stageError||copyError}</p>}
  <form className="composer" onSubmit={e=>{e.preventDefault();if(!p.busy&&p.draft.trim())void p.onSend()}}><textarea ref={input} id="composer" aria-label="消息" placeholder="输入问题或想法" value={p.draft} onChange={e=>p.setDraft(e.target.value)} onCompositionStart={()=>composing.current=true} onCompositionEnd={()=>composing.current=false} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&!composing.current&&e.nativeEvent.keyCode!==229){e.preventDefault();if(!p.busy&&p.draft.trim())void p.onSend()}}}/>{stagedFile&&<div className="attachment staged-attachment" role="status"><span>{stagedFile.name} · {stagedFile.size} 字节 · 已选择，尚未提交</span><button type="button" disabled={p.busy||fileWorking} onClick={()=>void submitFile()}>提交附件</button><button type="button" disabled={fileWorking} onClick={()=>setStaged(old=>{const next={...old};delete next[stageKey];return next})}>移除待提交附件</button></div>}{p.attachment&&<div className="attachment" role="status">{p.attachment.name} · {p.attachment.status==='reading'?'读取中':p.attachment.status==='registered'?'已完整登记，未声明语义理解':'读取失败'}{p.attachment.detail&&' · '+p.attachment.detail}</div>}<div className="composer-controls"><input ref={file} type="file" id="fileInput" className="file-input" accept=".txt,.md" aria-label="上传文本文件" disabled={p.busy} onChange={e=>{const selected=e.target.files?.[0];if(selected)stageFile(selected);e.target.value=''}}/><button type="button" disabled={p.busy} aria-label="附加文本资料" onClick={()=>file.current?.click()}>＋ 附加资料</button><small>TXT / Markdown · 64 KiB · 仅合成资料</small>{p.busy&&p.onStop?<button type="button" onClick={()=>void p.onStop!()}>停止</button>:<button id="send" className="send" disabled={p.busy||!p.draft.trim()} type="submit">{p.busy?'保存中':'发送'}</button>}</div></form>{p.turns.length===0&&<ul className="home-suggestions">{['帮我梳理一个原创计划','整理这份 TXT / Markdown 资料','更正已经记录的信息','核对不同来源的说法','看看当前能使用的背景','从一个简单问题开始'].map(text=><li key={text}><button onClick={()=>{p.setDraft(text);input.current?.focus()}}>{text}<span aria-hidden="true">→</span></button></li>)}</ul>}<p className="composer-note">{p.live?'开发验证不代表 HCL 效力证明；请勿输入真实私密信息':'演示记录不代表模型理解；请勿输入真实私密信息'}</p></main></section>
  {settings&&<ProductDialog label="设置" onClose={()=>setSettings(false)}><>{p.currentSettings&&<section aria-label="当前开发会话设置"><h2>当前开发会话</h2>{p.currentSettings}</section>}</><section><h2>形态与显示预览</h2><p>两种伙伴形态都保留，尚未选择最终品牌形象；装饰不代表监听或理解。</p><label>伙伴形态<select aria-label="伙伴形态" value={companion} onChange={e=>setCompanion(e.target.value as typeof companion)}><option value="orb">A · 悬浮核心</option><option value="receiver">B · 接收容器</option><option value="off">关闭</option></select></label><label>动态效果<select aria-label="动态效果" value={motion} onChange={e=>setMotion(e.target.value)}><option value="auto">跟随系统减少动态设置</option><option value="static">静态</option></select></label><label>表面效果<select aria-label="表面效果" value={transparency} onChange={e=>setTransparency(e.target.value)}><option value="auto">轻雾玻璃</option><option value="opaque">不透明可读回退</option></select></label></section><h2>下一次新建对话</h2><p>这些范围选项只用于下一次新建，不更改当前对话；刷新后恢复页面默认</p>{p.settings}{p.onExport&&<button onClick={()=>{setSettings(false);void p.onExport!()}}>导出当前会话</button>}<details><summary>高级与演示</summary><div>{p.environmentDetails}</div>{p.onInspect&&<button onClick={()=>{setSettings(false);p.onInspect!()}}>HCL Lab</button>}{p.onReset&&<button className="danger" onClick={()=>void reset()}>重置合成预览</button>}</details></ProductDialog>}
  {environment&&<ProductDialog label="演示环境" onClose={()=>setEnvironment(false)}><h2>{p.environment}</h2>{p.environmentDetails}</ProductDialog>}
  {search&&<ProductDialog label="搜索对话" onClose={()=>setSearch(false)}><label>{p.onSearch?'搜索原始对话与回答':'按标题查找'}<input aria-label="搜索历史" autoFocus value={query} onChange={e=>setQuery(e.target.value)}/></label>{p.onSearch?<><p className="muted">按当前权限读取记录；历史文本不是当前背景。更正与撤回同时呈现。</p>{searching&&<p role="status">查找中</p>}{searchError&&<p role="alert">{searchError}</p>}{hitRevision===p.historyRevision&&hits.map((hit,i)=><section className="search-hit" key={hit.run_id+'-'+i}><button onClick={()=>{void open(hit.conversation_id).then(()=>requestAnimationFrame(()=>{const target=document.querySelector<HTMLElement>('[data-run="'+CSS.escape(hit.run_id)+'"]');target?.scrollIntoView({block:'center'});target?.focus()}))}}>{hit.title} · {hit.scope||'会话'}{hit.historical?' · 历史记录':''}</button><p>{hit.snippet}</p>{hit.related_changes?.length? <details><summary>同会话更正与撤回</summary>{hit.related_changes.map((change,j)=><p key={j}>{change.action}：{change.old?.map(r=>r.content).join('；')} → {change.new?.map(r=>r.content).join('；')}</p>)}</details>:null}</section>)}{query.trim()&&!searching&&!hits.length&&!searchError&&<p>没有当前权限下的匹配记录</p>}</>:<><nav>{history.map(c=><button key={c.id} onClick={()=>void open(c.id)}>{c.title}</button>)}</nav>{history.length===0&&<p>没有匹配的对话</p>}</>}</ProductDialog>}

  {p.panels}
 </div></ReadingAnchorContext.Provider>
}
