import React,{useEffect,useState} from 'react';
import {api} from './api';
import {Dialog} from './panels';

type Inspection={mode:string;read_only:boolean;compare_enabled:boolean;compare_gate:string[];run:{run_id:string;state_version_before:number;state_version_after:number;route:string;selected_capability_ids:string[];operation_receipts:unknown[];run_receipt:{mode:string;outcome:string;usage:unknown;errors:string[];bridge_provenance?:unknown;actual_treatment?:string;development_only?:boolean};selected_context:unknown;errors:string[]};usage_scope:string;efficacy:string};
export function Lab({runId,onClose}:{runId:string;onClose:()=>void}){
 const [value,setValue]=useState<Inspection|null>(null),[error,setError]=useState('');
 useEffect(()=>{void api<Inspection>(`/v1/lab/runs/${runId}`).then(setValue).catch(e=>setError(String(e)));},[runId]);
 async function download(){try{const latest=await api<Inspection>(`/v1/lab/export/${runId}`);setValue(latest);const url=URL.createObjectURL(new Blob([JSON.stringify(latest,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`${latest.mode.toLowerCase()}-run-${runId}.json`;link.click();URL.revokeObjectURL(url);}catch(e){setError(String(e));}}
 return <Dialog label="HCL Lab" onClose={onClose}><h2>HCL Lab · {value?.mode==='EXPERIMENTAL'?'只读实验记录':'只读模拟记录'}</h2><p>{value?.mode==='EXPERIMENTAL'?'固定开发运行时，生产禁用；':'未接入真实 HCL；'}运行成功不代表认知效力。</p><button disabled>Base Compare（L3 后另需许可）</button>{error&&<p role="alert">{error}</p>}{value&&<><dl><dt>模式</dt><dd>{value.mode}</dd><dt>路由</dt><dd>{value.run.route==='CONTEXT_ASSISTED'?'CONTEXT_ASSISTED · generic':value.run.route}</dd><dt>结果</dt><dd>{value.run.run_receipt.outcome}</dd><dt>状态版本</dt><dd>{value.run.state_version_before} → {value.run.state_version_after}</dd><dt>能力</dt><dd>{value.run.selected_capability_ids.join(', ')||'无专门操作'}</dd></dl>{value.mode==='EXPERIMENTAL'&&<><p>实际处理：{value.run.run_receipt.actual_treatment}</p><h3>固定运行时来源</h3><pre>{JSON.stringify(value.run.run_receipt.bridge_provenance,null,2)}</pre></>}<h3>Usage（每 attempt）</h3><p>{value.usage_scope}</p><pre>{JSON.stringify(value.run.run_receipt.usage,null,2)}</pre><h3>显式 operation receipts</h3><pre>{JSON.stringify(value.run.operation_receipts,null,2)}</pre><h3>当前权限下的 context/snapshot</h3><pre>{JSON.stringify(value.run.selected_context,null,2)}</pre>{value.run.errors.length>0&&<p>Errors: {value.run.errors.join(', ')}</p>}<button onClick={()=>void download()}>导出当前权限下的 {value.mode==='EXPERIMENTAL'?'experimental':'mock'} 记录</button><p>L3 gate: {value.compare_gate.join(' / ')}</p></>}</Dialog>;
}
