import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,stream,type Conversation,type Run,type Ref} from './api';
import './style.css';

function App(){
 const [conversations,setConversations]=useState<Conversation[]>([]),[topics,setTopics]=useState<{id:string;title:string}[]>([]),[current,setCurrent]=useState<Conversation|null>(null),[runs,setRuns]=useState<Run[]>([]),[version,setVersion]=useState(0),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sidebar,setSidebar]=useState(true),[memory,setMemory]=useState('CONVERSATION'),[topic,setTopic]=useState(''),[source,setSource]=useState<{text:string;version:number;coverage:string}|null>(null);
 const input=useRef<HTMLTextAreaElement>(null),abort=useRef<AbortController|null>(null),active=useRef<Conversation|null>(null),sending=useRef(false),file=useRef<HTMLInputElement>(null),sourceFocus=useRef<HTMLElement|null>(null),sourceClose=useRef<HTMLButtonElement>(null);
 async function refreshLists(){setConversations(await api('/v1/conversations'));setTopics(await api('/v1/topics'));}
 async function load(c:Conversation){abort.current?.abort();active.current=c;setCurrent(c);setError('');const state=await api<{runs:Run[];state_version:number}>(`/v1/conversations/${c.id}`);if(active.current?.id!==c.id)return;setRuns(state.runs);setVersion(state.state_version);setBusy(state.runs.some(r=>r.pending));const pending=state.runs.find(r=>r.pending);if(pending)void watch(pending,c).catch(e=>{setError(String(e));setBusy(false);});}
 useEffect(()=>{void refreshLists();return()=>abort.current?.abort();},[]);
 useEffect(()=>{if(source)sourceClose.current?.focus();},[source]);
 async function create(){const c=await api<Conversation>('/v1/conversations',{topic_id:topic||null,memory,title:'新对话'});await refreshLists();await load(c);input.current?.focus();return c;}
 async function watch(run:Run,c:Conversation){const controller=new AbortController();abort.current?.abort();abort.current=controller;await stream(run.run_id,()=>{void api<Run>(`/v1/runs/${run.run_id}`).then(latest=>{if(active.current?.id===c.id)setRuns(old=>old.map(r=>r.run_id===latest.run_id?latest:r));});},controller.signal);if(active.current?.id===c.id){const state=await api<{runs:Run[];state_version:number}>(`/v1/conversations/${c.id}`);setRuns(state.runs);setVersion(state.state_version);setBusy(false);}}
 async function send(filename?:string,content?:string){if(sending.current||busy)return;sending.current=true;setBusy(true);setError('');const draft=content??text;
  try{let c=current;if(!c)c=await create();setBusy(true);const body={scope:{conversation_id:c.id,topic_id:c.topic_id,branch_id:'actual'},expected_state_version:version,allowed_memory_scope:c.memory,source_refs:[],model_resource_policy:{adapter:'MOCK',max_provider_calls:0,max_adapter_calls:1},idempotency_key:crypto.randomUUID(),event:{type:filename?'upload':'message',text:draft,...(filename?{filename}:{})}};
   const run=await api<Run>(filename?'/v1/sources':`/v1/conversations/${c.id}/events`,body);setVersion(run.state_version_after);setRuns(old=>[...old,run]);if(!filename)setText('');await watch(run,c);input.current?.focus();
  }catch(e){setError(String(e));setBusy(false);if(current){const state=await api<{state_version:number}>(`/v1/conversations/${current.id}`);setVersion(state.state_version);}}
  finally{sending.current=false;}
 }
 async function upload(f:File){if(!/\.(txt|md)$/i.test(f.name)){setError('仅支持 TXT / Markdown');return;}if(f.size>65536){setError('文件限制 64 KiB');return;}await send(f.name,await f.text());}
 async function stop(){const run=[...runs].reverse().find(r=>r.pending);if(run){await api(`/v1/runs/${run.run_id}/cancel`,{});if(current)await load(current);}setBusy(false);sending.current=false;input.current?.focus();}
 async function retry(run:Run){if(!current)return;setBusy(true);try{const next=await api<Run>(`/v1/runs/${run.run_id}/retry`,{idempotency_key:crypto.randomUUID()});setRuns(old=>[...old,next]);await watch(next,current);input.current?.focus();}catch(e){setError(String(e));setBusy(false);}}
 async function locate(ref:Ref,event:React.MouseEvent<HTMLButtonElement>){if(!current)return;sourceFocus.current=event.currentTarget;try{setSource(await api(`/v1/sources/${ref.source_id}?conversation_id=${current.id}&version=${ref.version}&sha256=${ref.sha256}`));}catch(e){setError(String(e));}}
 function closeSource(){setSource(null);sourceFocus.current?.focus();}
 return <div className={sidebar?'layout':'layout collapsed'}><header><button aria-label="切换侧栏" onClick={()=>setSidebar(!sidebar)}>☰</button><strong>HCL</strong><span>模拟运行：未接入真实 HCL 机制 · 仅合成数据</span></header>
 {sidebar&&<aside><button onClick={()=>void create().catch(e=>setError(String(e)))}>＋ 新对话</button><label>范围<select aria-label="记忆范围" value={memory} onChange={e=>{setMemory(e.target.value);if(e.target.value==='TEMPORARY')setTopic('');}}><option value="CONVERSATION">仅会话</option><option value="TOPIC">Topic</option><option value="TEMPORARY">临时（重启丢失）</option></select></label><label>Topic<select aria-label="Topic" value={topic} disabled={memory==='TEMPORARY'} onChange={e=>setTopic(e.target.value)}><option value="">无 Topic</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><button onClick={()=>void api('/v1/topics',{title:`项目 ${topics.length+1}`}).then(refreshLists).catch(e=>setError(String(e)))}>新建 Topic</button><small>以上范围用于新对话</small><nav aria-label="对话历史">{conversations.map((c,i)=><button key={c.id} aria-current={current?.id===c.id} onClick={()=>void load(c).catch(e=>setError(String(e)))}>{c.title} {i+1} · {c.memory==='TEMPORARY'?'临时':'已保存'}</button>)}</nav></aside>}
 <main><div className="conversation-title">{current?.title??'从一段对话开始'} {current?.topic_id&&<small> · Topic 内</small>}</div><div className="messages" aria-live="polite">{runs.length===0&&<section className="empty"><h1>有什么想一起理清？</h1><p>可以聊天、粘贴文本或上传 TXT / Markdown。当前是 provider-free 模拟。</p></section>}{runs.map(run=><article key={run.run_id}><div className="message-meta"><button onClick={e=>void locate(run.input_source_ref,e)}>查看输入原文 v{run.input_source_ref.version}</button><span>{run.run_receipt.outcome}{run.outdated?' · 旧版本':''}</span></div>{run.input_text&&<p className="user-message">{run.input_text}</p>}<p>{run.redacted?'依据已停止使用或删除。':run.answer?.text??run.stream.filter(e=>e.type==='answer.delta').map(e=>e.payload.text).join('')??''}</p>{!run.answer&&!run.pending&&!run.redacted&&<p>本次未发布完整回答。</p>}{run.answer?.citation_refs.map(ref=><button key={ref.source_id} onClick={e=>void locate(ref,e)}>来源 v{ref.version}</button>)}{['FAILED','CANCELLED'].includes(run.run_receipt.outcome)&&<button disabled={busy} onClick={()=>void retry(run)}>重试</button>}</article>)}</div>
 {error&&<p role="alert" className="error">{error}</p>}<div className="composer"><textarea ref={input} aria-label="消息" placeholder="输入消息；Shift+Enter 换行" value={text} maxLength={65536} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(text.trim())void send();}}}/><div><input ref={file} type="file" accept=".txt,.md" aria-label="上传文本文件" disabled={busy} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/>{busy?<button onClick={()=>void stop()}>停止</button>:<button disabled={!text.trim()} onClick={()=>void send()}>发送</button>}</div><small>64 KiB 上限 · 文件注册不表示已完整理解 · 临时正文仅留进程内存</small></div></main>
 {source&&<div className="overlay" role="dialog" aria-modal="true" aria-label="原文" onKeyDown={e=>{if(e.key==='Escape')closeSource();if(e.key==='Tab'){e.preventDefault();sourceClose.current?.focus();}}}><button ref={sourceClose} onClick={closeSource}>关闭原文</button><h2>原文版本 {source.version}</h2><p>覆盖：{source.coverage}（未声明完整理解）</p><pre>{source.text}</pre></div>}
 </div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
