import {providerDiagnostics,providerFailureSummary} from './provider-diagnostics';
import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,stream,type Conversation,type Run,type Ref} from './api';
import './style.css';
import {Lab} from './lab';
import {Memory,ExplainPanel,labels,type ContextRecord,type Explain} from './panels';
import {AssistantShell} from './AssistantShell';
import {ProductDialog} from './ProductDialog';
import {focusComposerAfterRun} from './MessageMenuAnchor';
import type {TurnView,AttachmentView} from './product-view';
import type {HistoryHit} from './history-view';
import {downloadJson} from './download';
import {SourceText} from './SourceText';
import {DevelopmentEntry} from './DevelopmentEntry';
import {MonthlyBudget} from './MonthlyBudget';

class ConversationReadError extends Error {}
class NavigationSupersededError extends Error {}
type ConversationReadState={id:string;phase:'loading'|'failed';message:string};

function App({live=false,cloud=false,trial=false,onLogout,account,provider='deepseek'}:{provider?:'deepseek'|'qwen';live?:boolean;cloud?:boolean;trial?:boolean;onLogout?:()=>void;account?:{scope:string;notice:string;renewing:boolean;logoutPending:boolean;generation?:{model:boolean;temporary:boolean;persistent:boolean;reason?:string}}}){
 const providerLabel=provider==='qwen'?'千问3.8-Max':'DeepSeek';
 const bridgeSource=provider==='qwen'?'Mira said, \"I believe that the team meeting was moved to Thursday.\"':'Ada said, \"I believe that the workshop starts Friday.\"';
 const bridgeQuery=provider==='qwen'?'What does Mira believe, and does this establish the actual meeting date?':'What does Ada believe?';
 const memberAccount=Boolean(account&&account.scope!=='owner');
 const [historyLoading,setHistoryLoading]=useState(true),[historyError,setHistoryError]=useState('');
 const [conversationRead,setConversationReadState]=useState<ConversationReadState|null>(null);
 const conversationReadRef=useRef<ConversationReadState|null>(null);
 function setConversationRead(value:ConversationReadState|null){conversationReadRef.current=value;setConversationReadState(value)}
 const loadFlight=useRef<{id:string;token:number;controller:AbortController;promise:Promise<boolean>}|null>(null);
 const historyVersion=useRef(0),historyAbort=useRef<AbortController|null>(null);
 const [synthetic,setSynthetic]=useState(trial),[providerRun,setProviderRun]=useState<string|null>(null);
 const [conversations,setConversations]=useState<Conversation[]>([]),[topics,setTopics]=useState<{id:string;title:string}[]>([]),[current,setCurrent]=useState<Conversation|null>(null),[runs,setRuns]=useState<Run[]>([]),[version,setVersionState]=useState(0),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reconciling,setReconciling]=useState(false),[sidebar,setSidebar]=useState(true),[memory,setMemory]=useState(trial||live&&!cloud?'TEMPORARY':'CONVERSATION'),[topic,setTopic]=useState(''),[source,setSource]=useState<{text:string;version:number;coverage:string;span?:number[]}|null>(null);
 const [managedSources,setManagedSources]=useState<{id:string;name:string;memory:string;stopped:boolean}[]>([]);
 const [lab,setLab]=useState<string|null>(null),[changeRun,setChangeRun]=useState<string|null>(null);
 const [sourceLoading,setSourceLoading]=useState(false),[explainLoading,setExplainLoading]=useState(false);
 const sourceBack=useRef<string|null>(null),sourceBackId=useRef<string|null>(null),channel=useRef<BroadcastChannel|null>(null);
 const [explain,setExplain]=useState<Explain|null>(null),[managed,setManaged]=useState<ContextRecord[]|null>(null);const panelFocus=useRef<HTMLElement|null>(null);
 const cancelRequested=useRef(false),versionRef=useRef(0);
 function setVersion(value:number){versionRef.current=value;setVersionState(value)}
 const drafts=useRef(new Map<string,string>()),draftOrigins=useRef(new Map<string,string>()),draftValue=useRef(''),navigation=useRef(0),panelVersion=useRef(0),exportEpoch=useRef(0);
 const [attachment,setAttachment]=useState<AttachmentView|null>(null),attachmentOrigin=useRef<string|null>(null),[loading,setLoading]=useState(false);
 function clearAttachment(){attachmentOrigin.current=null;setAttachment(null)}
 function draft(text:string){if(!text)draftOrigins.current.delete(active.current?.id||'new');draftValue.current=text;setText(text);drafts.current.set(active.current?.id||'new',text)}
 const attempt=useRef<{conversation:string;draft:string;filename?:string;bridge?:boolean;body:unknown}|null>(null);
 const input=useRef<HTMLTextAreaElement>(null),abort=useRef<AbortController|null>(null),reconciliationAbort=useRef<AbortController|null>(null),active=useRef<Conversation|null>(null),sending=useRef(false),revising=useRef(false),file=useRef<HTMLInputElement>(null),sourceFocus=useRef<HTMLElement|null>(null),sourceClose=useRef<HTMLButtonElement>(null);
 async function refreshLists(){
  const token=++historyVersion.current;historyAbort.current?.abort();const controller=new AbortController();historyAbort.current=controller;
  const timeout=setTimeout(()=>controller.abort(),15000);setHistoryLoading(true);
  try{
   const [nextConversations,nextTopics]=await Promise.all([api<Conversation[]>('/v1/conversations',undefined,controller.signal),api<{id:string;title:string}[]>('/v1/topics',undefined,controller.signal)]);
   if(token!==historyVersion.current)return;setConversations(nextConversations);setTopics(nextTopics);setHistoryError('');
  }catch(error){if(token===historyVersion.current){
   if(/^Error: (401|403):/.test(String(error))){setConversations([]);setTopics([]);setHistoryError('无法验证对话列表的访问权限，请确认登录状态后重试')}
   else setHistoryError('暂时无法加载对话列表，你可以重试；当前草稿会保留');
  }}finally{controller.abort();clearTimeout(timeout);if(token===historyVersion.current){setHistoryLoading(false);historyAbort.current=null}}
 }

 function cancelReconciliation(){const controller=reconciliationAbort.current;if(!controller)return;controller.abort();if(abort.current===controller)abort.current=null;reconciliationAbort.current=null;setReconciling(false);setBusy(false)}
 function cancelHistoryRead(interrupted=false){const flight=loadFlight.current;if(!flight)return;flight.controller.abort();if(abort.current===flight.controller)abort.current=null;loadFlight.current=null;if(interrupted&&active.current?.id===flight.id){setConversationRead({id:flight.id,phase:'failed',message:'读取已中止。草稿仍在，你可以重新读取这段对话。'});setBusy(false)}}
 function load(c:Conversation,preserve?:string):Promise<boolean>{
  const token=++navigation.current;panelVersion.current++;setLoading(true);cancelHistoryRead();cancelReconciliation();setReconciling(false);drafts.current.set(active.current?.id||'new',draftValue.current);abort.current?.abort();active.current=c;setCurrent(c);setRuns([]);setVersion(0);setLab(null);setProviderRun(null);setChangeRun(null);sourceBack.current=null;sourceBackId.current=null;setExplain(null);setManaged(null);setSource(null);setSourceLoading(false);setExplainLoading(false);clearAttachment();setError('');
  const value=preserve??drafts.current.get(c.id)??'';draftValue.current=value;setText(value);setBusy(false);setConversationRead({id:c.id,phase:'loading',message:'正在读取这段对话的记录，请稍候。'});
  const controller=new AbortController();abort.current=controller;let timedOut=false;const timeout=setTimeout(()=>{timedOut=true;controller.abort()},15000);const owns=()=>token===navigation.current&&active.current?.id===c.id;
  const promise=(async()=>{
   try{const state=await api<{runs:Run[];state_version:number}>(`/v1/conversations/${c.id}`,undefined,controller.signal);if(!owns())return false;
    const draftOrigin=draftOrigins.current.get(c.id);if(draftOrigin&&!state.runs.some(r=>!r.redacted&&r.input_source_ref.source_id===draftOrigin)){draftOrigins.current.delete(c.id);drafts.current.delete(c.id);draft('')}
    setConversationRead(null);setLoading(false);setRuns(state.runs);setVersion(state.state_version);setBusy(state.runs.some(r=>r.pending));const pending=state.runs.find(r=>r.pending);
    if(pending)void watch(pending,c).catch(error=>{if(owns()){setError(String(error));setBusy(false)}});return true;
   }catch(error){if(!owns())return false;const message=timedOut?'读取这段对话超时。草稿已保留，你可以重试。':/^Error: (401|403):/.test(String(error))?'暂时无法验证这段对话的访问权限，请确认账号后重试。':'暂时无法读取这段对话。草稿已保留，你可以重试。';setConversationRead({id:c.id,phase:'failed',message});setLoading(false);setBusy(false);throw new ConversationReadError(message,{cause:error})}
   finally{clearTimeout(timeout);controller.abort();if(abort.current===controller)abort.current=null;if(loadFlight.current?.controller===controller)loadFlight.current=null}
  })();loadFlight.current={id:c.id,token,controller,promise};return promise;
 }
 function openConversation(id:string){const c=conversations.find(value=>value.id===id);if(!c)return Promise.reject(new Error('这段对话已不可用，请重新加载对话列表'));const flight=loadFlight.current;return flight?.id===id&&flight.token===navigation.current&&!flight.controller.signal.aborted?flight.promise:load(c)}
 function retryConversationRead(){const c=active.current;if(c)void load(c,draftValue.current).catch(()=>{/* The owned reader keeps its recovery state. */})}

 useEffect(()=>{void refreshLists();if(typeof BroadcastChannel!=='undefined'){const bus=new BroadcastChannel('hcl-assistant-local-ui'+(account&&account.scope!=='owner'?':'+account.scope:''));channel.current=bus;bus.onmessage=event=>{if(event.data?.type!=='changed')return;exportEpoch.current++;panelVersion.current++;setSource(null);setSourceLoading(false);setExplainLoading(false);setExplain(null);setManaged(null);setLab(null);setProviderRun(null);setChangeRun(null);sourceBack.current=null;const removed=new Set<string>(event.data.deletedSources||[]);for(const [id,sourceId] of draftOrigins.current)if(removed.has(sourceId)){draftOrigins.current.delete(id);drafts.current.delete(id);if(active.current?.id===id)draft('')}const c=active.current;if(c)void load(c,draftValue.current).catch(()=>{/* The owned reader exposes recovery. */});void refreshLists()}}return()=>{historyVersion.current++;historyAbort.current?.abort();navigation.current++;panelVersion.current++;exportEpoch.current++;active.current=null;attempt.current=null;drafts.current.clear();draftOrigins.current.clear();draftValue.current='';attachmentOrigin.current=null;sourceBack.current=null;sourceBackId.current=null;cancelHistoryRead();abort.current?.abort();channel.current?.close()};},[]);
 useEffect(()=>{if(source)sourceClose.current?.focus();},[source]);
 async function create(preserveComposer=false,onCreated?:(conversation:Conversation,composerDraft:string)=>void){
  const token=++navigation.current,before=draftValue.current,previous=active.current?.id||'new';setLoading(true);cancelHistoryRead(true);cancelReconciliation();
  try{const c=await api<Conversation>('/v1/conversations',{topic_id:topic||null,memory,title:'新对话'});onCreated?.(c,navigation.current===token?draftValue.current:before);await refreshLists();if(navigation.current!==token)throw new NavigationSupersededError('对话已切换');
   const value=preserveComposer||draftValue.current!==before?draftValue.current:undefined,pending=load(c,value),loadToken=navigation.current;const applied=await pending;if(!applied||navigation.current!==loadToken||active.current?.id!==c.id)throw new NavigationSupersededError('对话已切换');drafts.current.set(previous,before);input.current?.focus();return c;
  }catch(error){if(token===navigation.current){setLoading(false);setError(String(error))}throw error}
 }

 async function watch(run:Run,c:Conversation){const token=navigation.current,controller=new AbortController();abort.current?.abort();abort.current=controller;await stream(run.run_id,()=>{void api<Run>(`/v1/runs/${run.run_id}`).then(latest=>{if(navigation.current===token&&active.current?.id===c.id)setRuns(old=>old.map(r=>r.run_id===latest.run_id?latest:r));}).catch(()=>{/* The stream finalizer owns interrupted-state recovery. */});},controller.signal);if(controller.signal.aborted)return;if(active.current?.id===c.id){const state=await api<{runs:Run[];state_version:number}>(`/v1/conversations/${c.id}`);if(navigation.current!==token||active.current?.id!==c.id)return;setRuns(state.runs);setVersion(state.state_version);setBusy(false);}}
 const generationBlocked=account?.renewing?'账号状态正在恢复，暂时无法发送':account?.generation?(!account.generation.model?(account.generation.reason||'模型服务暂未开放，已有记录仍可查看'):!account.generation[(current?.memory||memory)==='TEMPORARY'?'temporary':'persistent']?'当前账号暂不能使用这种对话范围，已有记录仍可查看':''):'';
 async function send(filename?:string,content?:string,bridge=false,onAccepted?:()=>void){if(sending.current||busy||loading||conversationReadRef.current)return;if(generationBlocked){setError(generationBlocked);return}if(live&&!synthetic){setError('请先确认本次仅使用原创合成输入');return}if(bridge&&current&&current.memory!=='TEMPORARY'){setError('HCL 合成测试需要临时会话，请新建临时会话');return}sending.current=true;cancelRequested.current=false;setReconciling(false);setBusy(true);setError('');const submitted=content??draftValue.current;let target=current,accepted=false,dispatchNavigation:number|undefined;
  const relevant=()=>((!target&&!active.current)||(target?.id===active.current?.id))&&(dispatchNavigation===undefined||dispatchNavigation===navigation.current);
  try{if(!target)target=await create(true,(created,composerDraft)=>{target=created;if(!drafts.current.has(created.id))drafts.current.set(created.id,composerDraft)});const c=target;const expected=active.current?.id===c.id?versionRef.current:(await api<{state_version:number}>(`/v1/conversations/${c.id}`)).state_version;if(active.current?.id===c.id)setBusy(true);let body:unknown={synthetic_input_confirmed:live&&synthetic,...(bridge?{development_execution:{schema_version:'1.0',capability_id:'belief_interpretation',query:bridgeQuery,input_class:'SYNTHETIC_NON_CONFIRMATION',fixture_family:'ORIGINAL_PRODUCT_SYNTHETIC',purpose:'DEVELOPMENT_INTEGRATION_ONLY',timeout_ms:3000}}:{}),scope:{conversation_id:c.id,topic_id:c.topic_id,branch_id:'actual'},expected_state_version:expected,allowed_memory_scope:c.memory,source_refs:[],model_resource_policy:{adapter:live?(provider==='qwen'?'QWEN':'DEEPSEEK'):'MOCK',max_provider_calls:live?1:0,max_adapter_calls:1},idempotency_key:crypto.randomUUID(),event:{type:filename?'upload':'message',text:submitted,...(filename?{filename}:{})}};
   if(attempt.current?.conversation===c.id&&attempt.current.draft===submitted&&attempt.current.filename===filename&&attempt.current.bridge===bridge)body=attempt.current.body;else attempt.current={conversation:c.id,draft:submitted,filename,bridge,body};
   dispatchNavigation=navigation.current;const run=await api<Run>(filename?'/v1/sources':`/v1/conversations/${c.id}/events`,body);accepted=true;onAccepted?.();attempt.current=null;exportEpoch.current++;channel.current?.postMessage({type:'changed'});if(relevant()){setVersion(run.state_version_after);setRuns(old=>old.some(r=>r.run_id===run.run_id)?old.map(r=>r.run_id===run.run_id?run:r):[...old,run]);if(!filename&&draftValue.current===submitted)draft('');if(filename){attachmentOrigin.current=run.input_source_ref.source_id;setAttachment({name:filename,status:'registered'})}}
   if(cancelRequested.current){await api(`/v1/runs/${run.run_id}/cancel`,{});if(relevant())await load(c,draftValue.current)}else if(relevant())await watch(run,c);if(relevant())focusComposerAfterRun(input.current);
  }catch(e){
   const owned=!(e instanceof NavigationSupersededError)&&relevant(),rawMessage=String(e),message=rawMessage==='TypeError: Failed to fetch'?(accepted?'连接暂时中断，请查看已记录的输入':'连接暂时中断，草稿已保留'):rawMessage,token=navigation.current;if(owned&&!(e instanceof ConversationReadError))setError(message);
   if(/\b(?:400|401|403|409|413|422|429):/.test(message))attempt.current=null;
   if(target&&owned&&dispatchNavigation!==undefined){
    setReconciling(true);
    // The accepted write may be unknown. Reconcile read-only before making the
    // same-key explicit retry available; navigation aborts this bounded read.
    const controller=new AbortController();abort.current?.abort();abort.current=controller;reconciliationAbort.current=controller;const timeout=setTimeout(()=>controller.abort(),15000);setError(message+'；正在核对提交状态，请稍候');
    try{const state=await api<{state_version:number;runs:Run[]}>(`/v1/conversations/${target.id}`,undefined,controller.signal);if(token===navigation.current&&relevant()){setVersion(state.state_version);setRuns(state.runs)}}
    catch{/* Draft/key remain recoverable; never retry an unknown event blindly. */}
    finally{clearTimeout(timeout);controller.abort();if(abort.current===controller)abort.current=null;if(reconciliationAbort.current===controller)reconciliationAbort.current=null;if(token===navigation.current&&relevant()){setReconciling(false);setError(message);setBusy(false)}}
   }else if(owned)setBusy(false);
  }
  finally{sending.current=false;}return {accepted,conversationId:target?.id};
 }
 async function upload(f:File,onAccepted?:()=>void){const target=active.current?.id,token=navigation.current;attachmentOrigin.current=null;setAttachment({name:f.name,status:'reading'});
  try{if(!/\.(txt|md)$/i.test(f.name))throw new Error('仅支持 TXT / Markdown');if(f.size>65536)throw new Error('文件限制 64 KiB');
   let content:string;try{content=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer())}catch{throw new Error('文本文件必须是有效 UTF-8')}if(content.includes('\0'))throw new Error('文本文件必须是有效 UTF-8 文本，不能包含 NUL');
   if(navigation.current!==token||active.current?.id!==target)throw new Error('读取期间对话已切换，请重新选择文件');return await send(f.name,content,false,onAccepted);
  }catch(e){if(navigation.current===token&&active.current?.id===target){setError(String(e));setAttachment({name:f.name,status:'failed',detail:String(e)})}return {accepted:false,conversationId:target}}
 }
 async function stop(){cancelRequested.current=true;const c=active.current,token=navigation.current,run=[...runs].reverse().find(r=>r.pending);if(!run&&sending.current)return;try{if(run){await api(`/v1/runs/${run.run_id}/cancel`,{});if(!c||token!==navigation.current||active.current?.id!==c.id)return;const pending=load(c,draftValue.current),loadToken=navigation.current;if(await pending&&loadToken===navigation.current&&active.current?.id===c.id)input.current?.focus();return}if(token===navigation.current&&(!c||active.current?.id===c.id)){setBusy(false);input.current?.focus()}}catch(e){if(token===navigation.current)setError(String(e))}}
 async function retry(run:Run){const c=active.current;if(!c)return;const token=navigation.current;setBusy(true);try{const next=await api<Run>(`/v1/runs/${run.run_id}/retry`,{idempotency_key:crypto.randomUUID()});if(token!==navigation.current||active.current?.id!==c.id)return;setRuns(old=>[...old,next]);await watch(next,c);if(token===navigation.current)focusComposerAfterRun(input.current)}catch(e){if(token===navigation.current){setError(String(e));setBusy(false)}}}
 async function contextReadFailure(error:unknown,c:Conversation){const message=String(error);if(!/^(?:Error: )?(403|409):/.test(message)){setError(message);return}exportEpoch.current++;if(draftOrigins.current.has(c.id)){draftOrigins.current.delete(c.id);drafts.current.delete(c.id);if(active.current?.id===c.id)draft('')}const refresh=load(c,draftValue.current),token=navigation.current;try{await refresh}catch{if(token===navigation.current&&active.current?.id===c.id&&draftOrigins.current.has(c.id)){draftOrigins.current.delete(c.id);drafts.current.delete(c.id);draft('')}}if(token===navigation.current&&active.current?.id===c.id)setError('来源或权限已变化，旧依据已清理。'+message)}
 async function locate(ref:Ref,event:React.MouseEvent<HTMLButtonElement>){if(!current)return;const id=current.id,token=navigation.current,panelToken=++panelVersion.current;sourceFocus.current=event.currentTarget;setSource(null);setExplain(null);setExplainLoading(false);setChangeRun(null);sourceBack.current=null;sourceBackId.current=null;setSourceLoading(true);try{const value=await api<{text:string;version:number;coverage:string}>(`/v1/sources/${ref.source_id}?conversation_id=${id}&version=${ref.version}&sha256=${ref.sha256}`);if(token===navigation.current&&active.current?.id===id&&panelToken===panelVersion.current){setSourceLoading(false);setSource({...value,span:ref.span})}}catch(e){if(token===navigation.current&&panelToken===panelVersion.current){setSourceLoading(false);void contextReadFailure(e,current)}}}
 async function openExplain(run:Run,event:React.MouseEvent<HTMLButtonElement>){if(!run.answer||!current)return;const id=current.id,token=navigation.current,panelToken=++panelVersion.current;panelFocus.current=event.currentTarget;setExplain(null);setSource(null);setSourceLoading(false);setChangeRun(null);sourceBack.current=null;sourceBackId.current=null;setExplainLoading(true);try{const value=await api<Explain>(`/v1/answers/${run.answer.answer_id}/explain`);if(token===navigation.current&&active.current?.id===id&&panelToken===panelVersion.current){setExplainLoading(false);setExplain(value)}}catch(e){if(token===navigation.current&&panelToken===panelVersion.current){setExplainLoading(false);void contextReadFailure(e,current)}}}
 async function openMemory(event?:React.MouseEvent<HTMLButtonElement>){if(!current)return;const id=current.id,token=navigation.current,panelToken=++panelVersion.current;if(event)panelFocus.current=event.currentTarget;setExplain(null);setSource(null);setSourceLoading(false);setExplainLoading(false);setChangeRun(null);setLab(null);setProviderRun(null);const state=await api<{managed_records:ContextRecord[];managed_sources:{id:string;name:string;memory:string;stopped:boolean}[]}>(`/v1/context?conversation_id=${id}&manage=1`);if(token===navigation.current&&active.current?.id===id&&panelToken===panelVersion.current){setManaged(state.managed_records);setManagedSources(state.managed_sources)}}
 async function revision(action:string,record:ContextRecord|{record_id:string},newRecord?:unknown){const c=active.current;if(!c)return;if(revising.current)throw new Error('正在提交另一条修订');const token=navigation.current,relevant=()=>token===navigation.current&&active.current?.id===c.id;let panelToken=panelVersion.current;revising.current=true;setBusy(true);const request={scope:{conversation_id:c.id,topic_id:c.topic_id,branch_id:'actual'},expected_state_version:versionRef.current,allowed_memory_scope:c.memory,source_refs:[],model_resource_policy:{adapter:'MOCK',max_provider_calls:0},idempotency_key:crypto.randomUUID(),event:{type:'revision',text:'用户修订背景',revisions:[{action,target_ids:[record.record_id],...(action==='SUPERSEDE'?{effective_time:new Date().toISOString()}:{}),...(newRecord?{new_record:newRecord}:{})}]}};
  try{const run=await api<Run>(`/v1/conversations/${c.id}/events`,request);exportEpoch.current++;channel.current?.postMessage({type:'changed',deletedSources:action==='DELETE'?('source_refs' in record?record.source_refs.map(ref=>ref.source_id):[record.record_id]):[]});if(action==='DELETE'){const removed=new Set('source_refs' in record?record.source_refs.map(ref=>ref.source_id):[record.record_id]);if(attachmentOrigin.current&&removed.has(attachmentOrigin.current)){attachmentOrigin.current=null;clearAttachment()}for(const [id,sourceId] of draftOrigins.current){if(removed.has(sourceId)){draftOrigins.current.delete(id);drafts.current.delete(id);if(active.current?.id===id)draft('')}}}if(!relevant())return;if(cloud&&c.memory==='TEMPORARY'&&['DELETE','STOP_USING'].includes(action)){panelVersion.current++;panelToken=panelVersion.current;setSource(null);setSourceLoading(false);setExplain(null);setExplainLoading(false);setLab(null);setProviderRun(null);setChangeRun(null);setManaged([]);setManagedSources([]);setRuns([run]);if(draftOrigins.current.has(c.id))draft('');clearAttachment()}else setRuns(old=>[...old,run]);setVersion(run.state_version_after);await watch(run,c);if(!relevant())return;const state=await api<{managed_records:ContextRecord[];managed_sources:{id:string;name:string;memory:string;stopped:boolean}[]}>(`/v1/context?conversation_id=${c.id}&manage=1`);if(relevant()&&panelToken===panelVersion.current){setManaged(state.managed_records);setManagedSources(state.managed_sources)}}catch(e){if(relevant()){const state=await api<{state_version:number;runs:Run[]}>(`/v1/conversations/${c.id}`);if(relevant()){setVersion(state.state_version);setRuns(state.runs)}throw e}}finally{if(relevant())setBusy(false);revising.current=false}
 }
 function closePanel(){panelVersion.current++;setSource(null);setSourceLoading(false);setExplainLoading(false);sourceBack.current=null;sourceBackId.current=null;setLab(null);setProviderRun(null);setChangeRun(null);setExplain(null);setManaged(null);panelFocus.current?.focus({preventScroll:true});}
 function closeSource(){panelVersion.current++;sourceBack.current=null;setSource(null);setSourceLoading(false);setExplainLoading(false);sourceFocus.current?.focus({preventScroll:true});}
 async function backToEvidence(){const answer=sourceBack.current,c=active.current;if(!answer||!c)return;const token=++panelVersion.current;try{const value=await api<Explain>(`/v1/answers/${answer}/explain`);if(token===panelVersion.current&&active.current?.id===c.id){setSource(null);setSourceLoading(false);setExplainLoading(false);setExplain(value);sourceBack.current=null}}catch(e){if(token===panelVersion.current&&active.current?.id===c.id)void contextReadFailure(e,c)}}
 async function exportCurrent(){const c=active.current;if(!c)return;const epoch=exportEpoch.current,token=navigation.current;try{const value=await api(`/v1/conversations/${c.id}`);if(epoch!==exportEpoch.current||token!==navigation.current||active.current?.id!==c.id){setError('数据或权限已变化，导出已取消，请重试');return}downloadJson(value,`synthetic-conversation-${c.id}.json`)}catch(e){setError(String(e))}}
 const turns:TurnView[]=runs.map(run=>({id:run.run_id,input:run.input_text,file:run.input_filename?{id:'source',label:run.input_filename,onActivate:e=>void locate(run.input_source_ref,e)}:undefined,output:run.redacted?'依据已停止使用或删除。':run.answer?.text??run.stream.filter(e=>e.type==='answer.delta').map(e=>e.payload.text).join(''),pending:run.pending,
  notice:run.errors?.some(e=>['request_budget_exhausted','cost_budget_exhausted'].includes(e))?'已到服务器批准的使用额度，本次没有发送新的模型请求。请等待管理员启用新的额度。':run.errors?.includes('concurrency_or_unconfirmed_transport')?'上一次模型请求尚未确认停止，本次未重复发送。请稍后查看记录，必要时联系管理员。':run.changes?.length?`背景变更已提交；${run.pending?'本次回答仍在处理中':run.answer?'本次回答已生成，旧回答尚未自动重新评估':`本次回答未完成（${run.run_receipt.outcome}），变更仍然保留`}。查看旧依据、新信息与影响。`:!run.pending&&!run.answer&&!run.redacted?`本次未发布完整回答（${run.run_receipt.outcome}），${run.run_receipt.provider?providerFailureSummary(run.run_receipt):'请先检查本次调用回执；不会自动重复请求。'}`:run.outdated?'当前记录版本不同；此处保留当时回答，未据此重写历史。':undefined,
  change:run.changes?.length?{id:'change',label:'查看变化',onActivate:()=>{closePanel();setChangeRun(run.run_id)}}:undefined,
  evidence:run.answer&&run.answer.citation_refs.length?{id:'evidence',label:'查看依据',onActivate:e=>void openExplain(run,e)}:undefined,
  sources:run.answer?.citation_refs.map(ref=>({id:ref.source_id,label:`来源 v${ref.version}`,onActivate:(e:React.MouseEvent<HTMLButtonElement>)=>void locate(ref,e)})),
  actions:[...(run.run_receipt.provider?[{id:'provider',label:'查看本次模型与 HCL 回执',onActivate:()=>{closePanel();setProviderRun(run.run_id)}}]:[]),{id:'source',label:`查看输入原文 v${run.input_source_ref.version}`,onActivate:e=>void locate(run.input_source_ref,e)},{id:'inspect',label:'在 Lab 检查',onActivate:e=>{closePanel();panelFocus.current=e.currentTarget;setLab(run.run_id)}}],
  retry:!live&&['FAILED','CANCELLED'].includes(run.run_receipt.outcome)?{id:'retry',label:'重试',disabled:busy,onActivate:()=>void retry(run)}:undefined}));
 const simulationControls=live?<section>{!memberAccount&&<label><input type="checkbox" checked={synthetic} onChange={event=>setSynthetic(event.target.checked)}/>本次仅使用原创合成输入，并使用服务器已批准额度</label>}<p>固定 Bridge 仅支持受限显式语法；英文原始合成样例用于开发验证，不代表中文通用能力。</p><button disabled={busy||loading||Boolean(conversationRead)||Boolean(generationBlocked)||!synthetic} onClick={()=>void send(undefined,bridgeSource,true)}>发送原创 HCL 合成样例（计一次调用）</button></section>:undefined;
 return <AssistantShell contextActive={Boolean(source||sourceLoading||explainLoading||explain||changeRun)} contextKind={source||sourceLoading?'source':changeRun?'revision':'evidence'} live={live} inputRef={input} environment={memberAccount?(account?.generation?.model?`合成内容体验 · ${providerLabel}`:'体验服务暂未开放 · 仅合成内容'):live?(account?.generation&&!account.generation.model?'模型服务暂未开放 · 仅合成输入':`开发态 · ${providerLabel} 真实调用 · 仅合成输入`):runs.some(r=>r.run_receipt.development_only)?'EXPERIMENTAL · 开发运行时 · 不连接模型':'交互演示，不连接模型'}
  environmentDetails={live?<><p>真实回答通过同一 Controller 与服务器模型调用。普通中文没有专门 HCL 处理时显示 NO_TREATMENT；不声称一般理解或效果增益。</p><p>调用会消耗已配置开发额度；失败和取消也可能计费，不自动重试。请只用原创合成内容，不输入真实私密资料。</p></>:<><p>本地 Python Controller / SQLite 合成环境。普通消息使用 MOCK；没有真实模型调用。已配置的固定 development runtime 仍只支持获准合成输入。</p><p>临时正文只在 API 进程内存，重启丢失；持久会话保存在本地 SQLite。生产身份和真实数据隐私未验证，provider费用为0。</p></>}
  historyLoading={historyLoading} historyError={historyError} onReloadHistory={()=>void refreshLists()} conversations={conversations.map(c=>({...c,project:c.topic_id||undefined}))} currentId={current?.id||null} title={current?.title||'新对话'} scope={current?current.memory==='TEMPORARY'?cloud?'临时 · 关闭或刷新页面丢失':'临时 · API重启丢失':current.topic_id?'项目内背景':'本会话背景':trial?'临时试用 · 关闭或刷新页面丢失':'新对话 · 默认本会话'} turns={turns} draft={text} setDraft={draft} onEdit={(id,value)=>{draft(value);const source=runs.find(r=>r.run_id===id)?.input_source_ref.source_id;if(current&&source)draftOrigins.current.set(current.id,source)}} conversationRead={conversationRead?{phase:conversationRead.phase,message:conversationRead.message,onRetry:retryConversationRead}:undefined} busy={busy||loading} busyLabel={conversationRead?.phase==='loading'?'正在读取':reconciling?'正在核对':undefined} sendDisabled={Boolean(conversationRead)||Boolean(generationBlocked)||(memberAccount&&!synthetic)} composerConsent={memberAccount?<label className="composer-consent"><input type="checkbox" checked={synthetic} onChange={event=>setSynthetic(event.target.checked)}/>本次仅使用原创合成内容，并使用账号可用额度</label>:undefined} error={error||generationBlocked||account?.notice||''} attachment={attachment}
  onNew={()=>create()} onOpen={openConversation} onSend={()=>send()} onUpload={upload} onStop={busy&&!reconciling?stop:undefined} onMemory={()=>void openMemory().catch(e=>setError(String(e)))} onSearch={query=>api<HistoryHit[]>(`/v1/history/search?q=${encodeURIComponent(query)}`)} historyRevision={version} onExport={exportCurrent} onInspect={runs.length?()=>{panelVersion.current++;setLab(runs[runs.length-1].run_id)}:undefined}
  currentSettings={memberAccount?undefined:simulationControls} advancedSettings={memberAccount?simulationControls:undefined}
  settings={<>{cloud&&provider==='qwen'&&<MonthlyBudget/>}{trial?<><p>临时试用只在当前标签页保留内容，刷新或关闭后丢失。本轮试用到期后自动停止。</p><button onClick={onLogout}>清空并离开本页会话</button></>:<>{cloud&&<><p>普通对话保存在此 HCLA 独立数据库，可跨设备恢复。临时内容只在当前请求和标签页内存；刷新或连接中断后可能无法恢复。</p><>{account?.notice&&<p role="status" className="account-status">{account.notice}</p>}<button disabled={account?.logoutPending} onClick={onLogout}>{account?.logoutPending?'正在退出…':'退出登录'}</button></></>}<label>记忆范围<select aria-label="记忆范围" value={memory} onChange={e=>{setMemory(e.target.value);if(e.target.value==='TEMPORARY')setTopic('')}}><option value="CONVERSATION">仅会话</option><option value="TOPIC">项目</option><option value="TEMPORARY">{cloud?'临时（刷新或关闭丢失）':'临时（API重启丢失）'}</option></select></label>{memory==='TOPIC'&&<><label>项目<select aria-label="Topic" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">选择项目</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><button onClick={()=>void api('/v1/topics',{title:`项目 ${topics.length+1}`}).then(refreshLists).catch(e=>setError(String(e)))}>新建项目</button></>}</>}</>}
  panels={<>{providerRun&&<ProductDialog label="本次调用回执" onClose={()=>setProviderRun(null)}><h2>同一次运行的真实记录</h2>{runs.filter(r=>r.run_id===providerRun).map(r=><section key={r.run_id}><p>Run：{r.run_id}</p><p>结果：{r.run_receipt.outcome}</p><p>请求模型：{r.run_receipt.provider?.requested_model||'未知'}；实际模型：{r.run_receipt.provider?.actual_model||'未返回'}</p><p>HCL：{r.run_receipt.actual_treatment||'NO_TREATMENT'}</p>{r.run_receipt.operations?.map((op,i)=><p key={i}>选择 {String(op.selected)} / 执行 {String(op.executed)} / 产出 {String(op.result_produced)} / 显式用于回答 {String(op.used_in_answer)}</p>)}<p>输入 tokens：{r.run_receipt.usage?.input_tokens??'未知'}；输出 tokens：{r.run_receipt.usage?.output_tokens??'未知'}；费用：{r.run_receipt.usage?.cost.amount??'未知'} {r.run_receipt.usage?.cost.currency||'USD'}</p>{providerDiagnostics(r.run_receipt).map(fact=><p key={fact.label}>{fact.label}：{fact.value}</p>)}<p>不会自动重复模型请求。费用未知不代表免费，最终以供应商账单为准。</p><p>仅开发集成证据；不证明 HCL 增益。未保存或展示隐藏推理。</p></section>)}</ProductDialog>}{lab&&<Lab runId={lab} onClose={closePanel}/>} {managed&&<Memory records={managed} sources={managedSources} onRevision={revision} onClose={closePanel}/>} {(explain||explainLoading||source||sourceLoading)&&<ProductDialog label={source||sourceLoading?"原文":"查看依据"} onClose={closePanel}>{explainLoading?<p role="status">正在读取当次回答依据</p>:sourceLoading?<p role="status">正在读取指定版本原文</p>:source?<><button className="source-return" hidden={!sourceBack.current} onClick={()=>void backToEvidence()}>返回依据</button><h2>原文版本 {source.version}</h2><p>覆盖：{source.coverage}（未声明完整理解）</p><SourceText text={source.text} span={source.span}/></>:explain&&<ExplainPanel embedded selectedSource={sourceBackId.current} value={explain} onClose={closePanel} onMemory={()=>void openMemory()} onSource={ref=>{const id=current!.id,token=navigation.current,panelToken=++panelVersion.current;sourceBack.current=explain!.answer_id;sourceBackId.current=ref.source_id;setSourceLoading(true);sourceFocus.current=panelFocus.current;void api<{text:string;version:number;coverage:string}>(`/v1/sources/${ref.source_id}?conversation_id=${current!.id}&version=${ref.version}&sha256=${ref.sha256}`).then(value=>{if(token===navigation.current&&active.current?.id===id&&panelToken===panelVersion.current){setSourceLoading(false);setExplainLoading(false);setSource({...value,span:ref.span})}}).catch(e=>{if(token===navigation.current&&panelToken===panelVersion.current){setSourceLoading(false);setExplainLoading(false);void contextReadFailure(e,current!)}})}}/>}</ProductDialog>}
  {changeRun&&<ProductDialog label="理解变化" onClose={closePanel}><h2>旧依据、新信息与影响</h2>{(runs.find(r=>r.run_id===changeRun)?.changes||[]).map((change,i)=><section key={i}><h3>{change.action==='GUESS'?'降回猜测':change.action==='SUPERSEDE'?'从现在变化':change.action==='HYPOTHETICAL_BRANCH'?'隔离假设':change.action}</h3><div className="change-columns"><section><strong>旧依据</strong>{change.old.map(r=><p key={r.record_id}>{labels[r.kind]||r.kind}：{r.content}</p>)}{!change.old.length&&<p>无可展示的旧依据，或已受当前权限限制</p>}</section><section><strong>新信息</strong>{change.new.map(r=><p key={r.record_id}>{labels[r.kind]||r.kind}：{r.content}</p>)}</section></div><p>{change.impact}</p><p>未重新评估：{change.not_reevaluated_count}；依赖失效：{change.invalidated_count}。弱化某解释不证明替代动机。</p></section>)}</ProductDialog>}
</>}/>

}

createRoot(document.getElementById('root')!).render(<DevelopmentEntry>{(live,cloud,onLogout,trial,account,provider)=><App provider={provider} key={account?.scope||(trial?'trial':'owner')} live={live} cloud={cloud} trial={trial} account={account} onLogout={onLogout}/>}</DevelopmentEntry>);
