import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,stream,type Conversation,type Run,type Ref} from './api';
import './style.css';
import {Lab} from './lab';
import {Memory,ExplainPanel,labels,type ContextRecord,type Explain} from './panels';
import {AssistantShell} from './AssistantShell';
import {ProductDialog} from './ProductDialog';
import type {TurnView,AttachmentView} from './product-view';
import type {HistoryHit} from './history-view';
import {downloadJson} from './download';
import {SourceText} from './SourceText';
import {DevelopmentEntry} from './DevelopmentEntry';

function App({live=false}:{live?:boolean}){
 const [synthetic,setSynthetic]=useState(false),[providerRun,setProviderRun]=useState<string|null>(null);
 const [conversations,setConversations]=useState<Conversation[]>([]),[topics,setTopics]=useState<{id:string;title:string}[]>([]),[current,setCurrent]=useState<Conversation|null>(null),[runs,setRuns]=useState<Run[]>([]),[version,setVersionState]=useState(0),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sidebar,setSidebar]=useState(true),[memory,setMemory]=useState(live?'TEMPORARY':'CONVERSATION'),[topic,setTopic]=useState(''),[source,setSource]=useState<{text:string;version:number;coverage:string;span?:number[]}|null>(null);
 const [managedSources,setManagedSources]=useState<{id:string;name:string;memory:string;stopped:boolean}[]>([]);
 const [lab,setLab]=useState<string|null>(null),[changeRun,setChangeRun]=useState<string|null>(null);
 const [sourceLoading,setSourceLoading]=useState(false),[explainLoading,setExplainLoading]=useState(false);
 const sourceBack=useRef<string|null>(null),sourceBackId=useRef<string|null>(null),channel=useRef<BroadcastChannel|null>(null);
 const [explain,setExplain]=useState<Explain|null>(null),[managed,setManaged]=useState<ContextRecord[]|null>(null);const panelFocus=useRef<HTMLElement|null>(null);
 const cancelRequested=useRef(false),versionRef=useRef(0);
 function setVersion(value:number){versionRef.current=value;setVersionState(value)}
 const drafts=useRef(new Map<string,string>()),draftOrigins=useRef(new Map<string,string>()),draftValue=useRef(''),navigation=useRef(0),panelVersion=useRef(0),exportEpoch=useRef(0);
 const [attachment,setAttachment]=useState<AttachmentView|null>(null),attachmentOrigin=useRef<string|null>(null),[loading,setLoading]=useState(false);
 function clearAttachment(){attachmentOrigin.current=null;setAttachment(null)}
 function draft(text:string){if(!text)draftOrigins.current.delete(active.current?.id||'new');draftValue.current=text;setText(text);drafts.current.set(active.current?.id||'new',text)}
 const attempt=useRef<{conversation:string;draft:string;filename?:string;bridge?:boolean;body:unknown}|null>(null);
 const input=useRef<HTMLTextAreaElement>(null),abort=useRef<AbortController|null>(null),active=useRef<Conversation|null>(null),sending=useRef(false),revising=useRef(false),file=useRef<HTMLInputElement>(null),sourceFocus=useRef<HTMLElement|null>(null),sourceClose=useRef<HTMLButtonElement>(null);
 async function refreshLists(){setConversations(await api('/v1/conversations'));setTopics(await api('/v1/topics'));}
 async function load(c:Conversation,preserve?:string){
  const token=++navigation.current;panelVersion.current++;setLoading(true);drafts.current.set(active.current?.id||'new',draftValue.current);abort.current?.abort();active.current=c;setCurrent(c);setRuns([]);setVersion(0);setLab(null);setProviderRun(null);setChangeRun(null);sourceBack.current=null;sourceBackId.current=null;setExplain(null);setManaged(null);setSource(null);setSourceLoading(false);setExplainLoading(false);clearAttachment();setError('');
  const value=preserve??drafts.current.get(c.id)??'';draftValue.current=value;setText(value);setBusy(false);
  const state=await api<{runs:Run[];state_version:number}>(`/v1/conversations/${c.id}`).catch(error=>{if(token===navigation.current)setLoading(false);throw error});if(navigation.current!==token||active.current?.id!==c.id)return;setLoading(false);setRuns(state.runs);setVersion(state.state_version);setBusy(state.runs.some(r=>r.pending));const pending=state.runs.find(r=>r.pending);if(pending)void watch(pending,c).catch(e=>{if(active.current?.id===c.id){setError(String(e));setBusy(false)}});
 }
 useEffect(()=>{void refreshLists();if(typeof BroadcastChannel!=='undefined'){const bus=new BroadcastChannel('hcl-assistant-local-ui');channel.current=bus;bus.onmessage=event=>{if(event.data?.type!=='changed')return;exportEpoch.current++;panelVersion.current++;setSource(null);setSourceLoading(false);setExplainLoading(false);setExplain(null);setManaged(null);setLab(null);setProviderRun(null);setChangeRun(null);sourceBack.current=null;const removed=new Set<string>(event.data.deletedSources||[]);for(const [id,sourceId] of draftOrigins.current)if(removed.has(sourceId)){draftOrigins.current.delete(id);drafts.current.delete(id);if(active.current?.id===id)draft('')}const c=active.current;if(c)void load(c,draftValue.current).catch(e=>setError(String(e)));void refreshLists()}}return()=>{abort.current?.abort();channel.current?.close()};},[]);
 useEffect(()=>{if(source)sourceClose.current?.focus();},[source]);
 async function create(preserveComposer=false){const token=++navigation.current,before=draftValue.current,previous=active.current?.id||'new';setLoading(true);try{const c=await api<Conversation>('/v1/conversations',{topic_id:topic||null,memory,title:'新对话'});await refreshLists();if(navigation.current===token){const value=preserveComposer||draftValue.current!==before?draftValue.current:undefined;await load(c,value);drafts.current.set(previous,before);if(active.current?.id===c.id)input.current?.focus()}return c;}catch(error){if(token===navigation.current)setLoading(false);throw error}}
 async function watch(run:Run,c:Conversation){const token=navigation.current,controller=new AbortController();abort.current?.abort();abort.current=controller;await stream(run.run_id,()=>{void api<Run>(`/v1/runs/${run.run_id}`).then(latest=>{if(navigation.current===token&&active.current?.id===c.id)setRuns(old=>old.map(r=>r.run_id===latest.run_id?latest:r));});},controller.signal);if(controller.signal.aborted)return;if(active.current?.id===c.id){const state=await api<{runs:Run[];state_version:number}>(`/v1/conversations/${c.id}`);if(navigation.current!==token||active.current?.id!==c.id)return;setRuns(state.runs);setVersion(state.state_version);setBusy(false);}}
 async function send(filename?:string,content?:string,bridge=false,onAccepted?:()=>void){if(sending.current||busy)return;if(live&&!synthetic){setError('请先确认本次仅使用原创合成输入');return}if(bridge&&current&&current.memory!=='TEMPORARY'){setError('HCL 合成测试需要临时会话，请新建临时会话');return}sending.current=true;cancelRequested.current=false;setBusy(true);setError('');const submitted=content??draftValue.current;let target=current,accepted=false;
  try{if(!target)target=await create(true);const c=target;const expected=active.current?.id===c.id?versionRef.current:(await api<{state_version:number}>(`/v1/conversations/${c.id}`)).state_version;if(active.current?.id===c.id)setBusy(true);let body:unknown={synthetic_input_confirmed:live&&synthetic,...(bridge?{development_execution:{schema_version:'1.0',capability_id:'belief_interpretation',query:'What does Ada believe?',input_class:'SYNTHETIC_NON_CONFIRMATION',fixture_family:'ORIGINAL_PRODUCT_SYNTHETIC',purpose:'DEVELOPMENT_INTEGRATION_ONLY',timeout_ms:3000}}:{}),scope:{conversation_id:c.id,topic_id:c.topic_id,branch_id:'actual'},expected_state_version:expected,allowed_memory_scope:c.memory,source_refs:[],model_resource_policy:{adapter:live?'DEEPSEEK':'MOCK',max_provider_calls:live?1:0,max_adapter_calls:1},idempotency_key:crypto.randomUUID(),event:{type:filename?'upload':'message',text:submitted,...(filename?{filename}:{})}};
   if(attempt.current?.conversation===c.id&&attempt.current.draft===submitted&&attempt.current.filename===filename&&attempt.current.bridge===bridge)body=attempt.current.body;else attempt.current={conversation:c.id,draft:submitted,filename,bridge,body};
   const run=await api<Run>(filename?'/v1/sources':`/v1/conversations/${c.id}/events`,body);accepted=true;onAccepted?.();attempt.current=null;exportEpoch.current++;channel.current?.postMessage({type:'changed'});if(active.current?.id===c.id){setVersion(run.state_version_after);setRuns(old=>old.some(r=>r.run_id===run.run_id)?old.map(r=>r.run_id===run.run_id?run:r):[...old,run]);if(!filename&&draftValue.current===submitted)draft('');if(filename){attachmentOrigin.current=run.input_source_ref.source_id;setAttachment({name:filename,status:'registered'})}}
   if(cancelRequested.current){await api(`/v1/runs/${run.run_id}/cancel`,{});if(active.current?.id===c.id){await load(c,draftValue.current);setBusy(false)}}else if(active.current?.id===c.id)await watch(run,c);if(active.current?.id===c.id)input.current?.focus();
  }catch(e){const relevant=(!target&&!active.current)||(target?.id===active.current?.id);if(relevant){setError(String(e));setBusy(false)}if(/\b(?:400|401|403|409|413|422|429):/.test(String(e)))attempt.current=null;if(target&&relevant){const token=navigation.current;try{const state=await api<{state_version:number;runs:Run[]}>(`/v1/conversations/${target.id}`);if(navigation.current===token&&active.current?.id===target.id){setVersion(state.state_version);setRuns(state.runs)}}catch{/* Draft/key remain recoverable; never retry an unknown event blindly. */}}}
  finally{sending.current=false;}return {accepted,conversationId:target?.id};
 }
 async function upload(f:File,onAccepted?:()=>void){const target=active.current?.id,token=navigation.current;attachmentOrigin.current=null;setAttachment({name:f.name,status:'reading'});
  try{if(!/\.(txt|md)$/i.test(f.name))throw new Error('仅支持 TXT / Markdown');if(f.size>65536)throw new Error('文件限制 64 KiB');
   let content:string;try{content=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer())}catch{throw new Error('文本文件必须是有效 UTF-8')}if(content.includes('\0'))throw new Error('文本文件必须是有效 UTF-8 文本，不能包含 NUL');
   if(navigation.current!==token||active.current?.id!==target)throw new Error('读取期间对话已切换，请重新选择文件');return await send(f.name,content,false,onAccepted);
  }catch(e){if(navigation.current===token&&active.current?.id===target){setError(String(e));setAttachment({name:f.name,status:'failed',detail:String(e)})}return {accepted:false,conversationId:target}}
 }
 async function stop(){cancelRequested.current=true;const c=active.current,token=navigation.current,run=[...runs].reverse().find(r=>r.pending);if(!run&&sending.current)return;try{if(run){await api(`/v1/runs/${run.run_id}/cancel`,{});if(c&&token===navigation.current&&active.current?.id===c.id)await load(c,draftValue.current)}if(!c||active.current?.id===c.id){setBusy(false);input.current?.focus()}}catch(e){if(token===navigation.current)setError(String(e))}}
 async function retry(run:Run){const c=active.current;if(!c)return;const token=navigation.current;setBusy(true);try{const next=await api<Run>(`/v1/runs/${run.run_id}/retry`,{idempotency_key:crypto.randomUUID()});if(token!==navigation.current||active.current?.id!==c.id)return;setRuns(old=>[...old,next]);await watch(next,c);if(token===navigation.current)input.current?.focus()}catch(e){if(token===navigation.current){setError(String(e));setBusy(false)}}}
 async function locate(ref:Ref,event:React.MouseEvent<HTMLButtonElement>){if(!current)return;const id=current.id,token=navigation.current,panelToken=++panelVersion.current;sourceFocus.current=event.currentTarget;setSource(null);setExplain(null);setExplainLoading(false);setChangeRun(null);sourceBack.current=null;sourceBackId.current=null;setSourceLoading(true);try{const value=await api<{text:string;version:number;coverage:string}>(`/v1/sources/${ref.source_id}?conversation_id=${id}&version=${ref.version}&sha256=${ref.sha256}`);if(token===navigation.current&&active.current?.id===id&&panelToken===panelVersion.current){setSourceLoading(false);setSource({...value,span:ref.span})}}catch(e){if(token===navigation.current&&panelToken===panelVersion.current){setSourceLoading(false);setError(String(e))}}}
 async function openExplain(run:Run,event:React.MouseEvent<HTMLButtonElement>){if(!run.answer||!current)return;const id=current.id,token=navigation.current,panelToken=++panelVersion.current;panelFocus.current=event.currentTarget;setExplain(null);setSource(null);setSourceLoading(false);setChangeRun(null);sourceBack.current=null;sourceBackId.current=null;setExplainLoading(true);try{const value=await api<Explain>(`/v1/answers/${run.answer.answer_id}/explain`);if(token===navigation.current&&active.current?.id===id&&panelToken===panelVersion.current){setExplainLoading(false);setExplain(value)}}catch(e){if(token===navigation.current&&panelToken===panelVersion.current){setExplainLoading(false);setError(String(e))}}}
 async function openMemory(event?:React.MouseEvent<HTMLButtonElement>){if(!current)return;const id=current.id,token=navigation.current,panelToken=++panelVersion.current;if(event)panelFocus.current=event.currentTarget;setExplain(null);setSource(null);setSourceLoading(false);setExplainLoading(false);setChangeRun(null);setLab(null);setProviderRun(null);const state=await api<{managed_records:ContextRecord[];managed_sources:{id:string;name:string;memory:string;stopped:boolean}[]}>(`/v1/context?conversation_id=${id}&manage=1`);if(token===navigation.current&&active.current?.id===id&&panelToken===panelVersion.current){setManaged(state.managed_records);setManagedSources(state.managed_sources)}}
 async function revision(action:string,record:ContextRecord|{record_id:string},newRecord?:unknown){const c=active.current;if(!c)return;if(revising.current)throw new Error('正在提交另一条修订');const token=navigation.current,panelToken=panelVersion.current,relevant=()=>token===navigation.current&&active.current?.id===c.id;revising.current=true;setBusy(true);const request={scope:{conversation_id:c.id,topic_id:c.topic_id,branch_id:'actual'},expected_state_version:versionRef.current,allowed_memory_scope:c.memory,source_refs:[],model_resource_policy:{adapter:'MOCK',max_provider_calls:0},idempotency_key:crypto.randomUUID(),event:{type:'revision',text:'用户修订背景',revisions:[{action,target_ids:[record.record_id],...(action==='SUPERSEDE'?{effective_time:new Date().toISOString()}:{}),...(newRecord?{new_record:newRecord}:{})}]}};
  try{const run=await api<Run>(`/v1/conversations/${c.id}/events`,request);exportEpoch.current++;channel.current?.postMessage({type:'changed',deletedSources:action==='DELETE'?('source_refs' in record?record.source_refs.map(ref=>ref.source_id):[record.record_id]):[]});if(action==='DELETE'){const removed=new Set('source_refs' in record?record.source_refs.map(ref=>ref.source_id):[record.record_id]);if(attachmentOrigin.current&&removed.has(attachmentOrigin.current)){attachmentOrigin.current=null;clearAttachment()}for(const [id,sourceId] of draftOrigins.current){if(removed.has(sourceId)){draftOrigins.current.delete(id);drafts.current.delete(id);if(active.current?.id===id)draft('')}}}if(!relevant())return;setRuns(old=>[...old,run]);setVersion(run.state_version_after);await watch(run,c);if(!relevant())return;const state=await api<{managed_records:ContextRecord[];managed_sources:{id:string;name:string;memory:string;stopped:boolean}[]}>(`/v1/context?conversation_id=${c.id}&manage=1`);if(relevant()&&panelToken===panelVersion.current){setManaged(state.managed_records);setManagedSources(state.managed_sources)}}catch(e){if(relevant()){const state=await api<{state_version:number;runs:Run[]}>(`/v1/conversations/${c.id}`);if(relevant()){setVersion(state.state_version);setRuns(state.runs)}throw e}}finally{if(relevant())setBusy(false);revising.current=false}
 }
 function closePanel(){panelVersion.current++;setSource(null);setSourceLoading(false);setExplainLoading(false);sourceBack.current=null;sourceBackId.current=null;setLab(null);setProviderRun(null);setChangeRun(null);setExplain(null);setManaged(null);panelFocus.current?.focus({preventScroll:true});}
 function closeSource(){panelVersion.current++;sourceBack.current=null;setSource(null);setSourceLoading(false);setExplainLoading(false);sourceFocus.current?.focus({preventScroll:true});}
 async function backToEvidence(){const answer=sourceBack.current,c=active.current;if(!answer||!c)return;const token=++panelVersion.current;try{const value=await api<Explain>(`/v1/answers/${answer}/explain`);if(token===panelVersion.current&&active.current?.id===c.id){setSource(null);setSourceLoading(false);setExplainLoading(false);setExplain(value);sourceBack.current=null;const id=sourceBackId.current;if(id)requestAnimationFrame(()=>document.querySelector<HTMLElement>('[data-source-id="'+CSS.escape(id)+'"]')?.focus({preventScroll:true}))}}catch(e){setError(String(e))}}
 async function exportCurrent(){const c=active.current;if(!c)return;const epoch=exportEpoch.current,token=navigation.current;try{const value=await api(`/v1/conversations/${c.id}`);if(epoch!==exportEpoch.current||token!==navigation.current||active.current?.id!==c.id){setError('数据或权限已变化，导出已取消，请重试');return}downloadJson(value,`synthetic-conversation-${c.id}.json`)}catch(e){setError(String(e))}}
 const turns:TurnView[]=runs.map(run=>({id:run.run_id,input:run.input_text,file:run.input_filename?{id:'source',label:run.input_filename,onActivate:e=>void locate(run.input_source_ref,e)}:undefined,output:run.redacted?'依据已停止使用或删除。':run.answer?.text??run.stream.filter(e=>e.type==='answer.delta').map(e=>e.payload.text).join(''),pending:run.pending,
  notice:run.changes?.length?`背景变更已提交；${run.pending?'本次回答仍在处理中':run.answer?'本次回答已生成，旧回答尚未自动重新评估':`本次回答未完成（${run.run_receipt.outcome}），变更仍然保留`}。查看旧依据、新信息与影响。`:!run.pending&&!run.answer&&!run.redacted?`本次未发布完整回答（${run.run_receipt.outcome}），可以检查记录或重试。`:run.outdated?'当前记录版本不同；此处保留当时回答，未据此重写历史。':undefined,
  change:run.changes?.length?{id:'change',label:'查看变化',onActivate:()=>{closePanel();setChangeRun(run.run_id)}}:undefined,
  evidence:run.answer&&run.answer.citation_refs.length?{id:'evidence',label:'查看依据',onActivate:e=>void openExplain(run,e)}:undefined,
  sources:run.answer?.citation_refs.map(ref=>({id:ref.source_id,label:`来源 v${ref.version}`,onActivate:(e:React.MouseEvent<HTMLButtonElement>)=>void locate(ref,e)})),
  actions:[...(run.run_receipt.provider?[{id:'provider',label:'查看本次模型与 HCL 回执',onActivate:()=>{closePanel();setProviderRun(run.run_id)}}]:[]),{id:'source',label:`查看输入原文 v${run.input_source_ref.version}`,onActivate:e=>void locate(run.input_source_ref,e)},{id:'inspect',label:'在 Lab 检查',onActivate:e=>{closePanel();panelFocus.current=e.currentTarget;setLab(run.run_id)}}],
  retry:!live&&['FAILED','CANCELLED'].includes(run.run_receipt.outcome)?{id:'retry',label:'重试',disabled:busy,onActivate:()=>void retry(run)}:undefined}));
 return <AssistantShell contextActive={Boolean(source||sourceLoading||explainLoading||explain||changeRun)} contextKind={source||sourceLoading?'source':changeRun?'revision':'evidence'} live={live} inputRef={input} environment={live?'开发态 · DeepSeek 真实调用 · 仅合成输入':runs.some(r=>r.run_receipt.development_only)?'EXPERIMENTAL · 开发运行时 · 不连接模型':'交互演示，不连接模型'}
  environmentDetails={live?<><p>真实回答通过同一 Controller 与服务器模型调用。普通中文没有专门 HCL 处理时显示 NO_TREATMENT；不声称一般理解或效果增益。</p><p>调用会消耗已配置开发额度；失败和取消也可能计费，不自动重试。请只用原创合成内容，不输入真实私密资料。</p></>:<><p>本地 Python Controller / SQLite 合成环境。普通消息使用 MOCK；没有真实模型调用。已配置的固定 development runtime 仍只支持获准合成输入。</p><p>临时正文只在 API 进程内存，重启丢失；持久会话保存在本地 SQLite。生产身份和真实数据隐私未验证，provider费用为0。</p></>}
  conversations={conversations.map(c=>({...c,project:c.topic_id||undefined}))} currentId={current?.id||null} title={current?.title||'新对话'} scope={current?current.memory==='TEMPORARY'?'临时 · API重启丢失':current.topic_id?'项目内背景':'本会话背景':'新对话 · 默认本会话'} turns={turns} draft={text} setDraft={draft} onEdit={(id,value)=>{draft(value);const source=runs.find(r=>r.run_id===id)?.input_source_ref.source_id;if(current&&source)draftOrigins.current.set(current.id,source)}} busy={busy||loading} error={error} attachment={attachment}
  onNew={()=>create().catch(e=>setError(String(e)))} onOpen={id=>{const c=conversations.find(c=>c.id===id);if(c)return load(c).catch(e=>setError(String(e)))}} onSend={()=>send()} onUpload={upload} onStop={busy?stop:undefined} onMemory={()=>void openMemory().catch(e=>setError(String(e)))} onSearch={query=>api<HistoryHit[]>(`/v1/history/search?q=${encodeURIComponent(query)}`)} historyRevision={version} onExport={exportCurrent} onInspect={runs.length?()=>{panelVersion.current++;setLab(runs[runs.length-1].run_id)}:undefined}
  currentSettings={live?<section><label><input type="checkbox" checked={synthetic} onChange={event=>setSynthetic(event.target.checked)}/>本次仅使用原创合成输入，并使用服务器已批准额度</label><p>固定 Bridge 仅支持受限显式语法；英文原始合成样例用于开发验证，不代表中文通用能力。</p><button disabled={busy||!synthetic} onClick={()=>void send(undefined,'Ada said, "I believe that the workshop starts Friday."',true)}>发送原创 HCL 合成样例（计一次调用）</button></section>:undefined}
  settings={<><label>记忆范围<select aria-label="记忆范围" value={memory} onChange={e=>{setMemory(e.target.value);if(e.target.value==='TEMPORARY')setTopic('')}}><option value="CONVERSATION">仅会话</option><option value="TOPIC">项目</option><option value="TEMPORARY">临时（API重启丢失）</option></select></label>{memory==='TOPIC'&&<><label>项目<select aria-label="Topic" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">选择项目</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><button onClick={()=>void api('/v1/topics',{title:`项目 ${topics.length+1}`}).then(refreshLists).catch(e=>setError(String(e)))}>新建项目</button></>}</>}
  panels={<>{providerRun&&<ProductDialog label="本次调用回执" onClose={()=>setProviderRun(null)}><h2>同一次运行的真实记录</h2>{runs.filter(r=>r.run_id===providerRun).map(r=><section key={r.run_id}><p>Run：{r.run_id}</p><p>结果：{r.run_receipt.outcome}</p><p>请求模型：{r.run_receipt.provider?.requested_model||'未知'}；实际模型：{r.run_receipt.provider?.actual_model||'未返回'}</p><p>HCL：{r.run_receipt.actual_treatment||'NO_TREATMENT'}</p>{r.run_receipt.operations?.map((op,i)=><p key={i}>选择 {String(op.selected)} / 执行 {String(op.executed)} / 产出 {String(op.result_produced)} / 显式用于回答 {String(op.used_in_answer)}</p>)}<p>输入 tokens：{r.run_receipt.usage?.input_tokens??'未知'}；输出 tokens：{r.run_receipt.usage?.output_tokens??'未知'}；费用：{r.run_receipt.usage?.cost.amount??'未知'} USD</p><p>仅开发集成证据；不证明 HCL 增益。未保存或展示隐藏推理。</p></section>)}</ProductDialog>}{lab&&<Lab runId={lab} onClose={closePanel}/>} {managed&&<Memory records={managed} sources={managedSources} onRevision={revision} onClose={closePanel}/>} {(explain||explainLoading||source||sourceLoading)&&<ProductDialog label={source||sourceLoading?"原文":"查看依据"} onClose={closePanel}>{explainLoading?<p role="status">正在读取当次回答依据</p>:sourceLoading?<p role="status">正在读取指定版本原文</p>:source?<><button className="source-return" hidden={!sourceBack.current} onClick={()=>void backToEvidence()}>返回依据</button><h2>原文版本 {source.version}</h2><p>覆盖：{source.coverage}（未声明完整理解）</p><SourceText text={source.text} span={source.span}/></>:explain&&<ExplainPanel embedded selectedSource={sourceBackId.current} value={explain} onClose={closePanel} onMemory={()=>void openMemory()} onSource={ref=>{const id=current!.id,token=navigation.current,panelToken=++panelVersion.current;sourceBack.current=explain!.answer_id;sourceBackId.current=ref.source_id;setSourceLoading(true);sourceFocus.current=panelFocus.current;void api<{text:string;version:number;coverage:string}>(`/v1/sources/${ref.source_id}?conversation_id=${current!.id}&version=${ref.version}&sha256=${ref.sha256}`).then(value=>{if(token===navigation.current&&active.current?.id===id&&panelToken===panelVersion.current){setSourceLoading(false);setExplainLoading(false);setSource({...value,span:ref.span})}}).catch(e=>{if(token===navigation.current&&panelToken===panelVersion.current){setSourceLoading(false);setExplainLoading(false);setError(String(e))}})}}/>}</ProductDialog>}
  {changeRun&&<ProductDialog label="理解变化" onClose={closePanel}><h2>旧依据、新信息与影响</h2>{(runs.find(r=>r.run_id===changeRun)?.changes||[]).map((change,i)=><section key={i}><h3>{change.action==='GUESS'?'降回猜测':change.action==='SUPERSEDE'?'从现在变化':change.action==='HYPOTHETICAL_BRANCH'?'隔离假设':change.action}</h3><div className="change-columns"><section><strong>旧依据</strong>{change.old.map(r=><p key={r.record_id}>{labels[r.kind]||r.kind}：{r.content}</p>)}{!change.old.length&&<p>无可展示的旧依据，或已受当前权限限制</p>}</section><section><strong>新信息</strong>{change.new.map(r=><p key={r.record_id}>{labels[r.kind]||r.kind}：{r.content}</p>)}</section></div><p>{change.impact}</p><p>未重新评估：{change.not_reevaluated_count}；依赖失效：{change.invalidated_count}。弱化某解释不证明替代动机。</p></section>)}</ProductDialog>}
</>}/>

}

createRoot(document.getElementById('root')!).render(<DevelopmentEntry>{live=><App live={live}/>}</DevelopmentEntry>);
