import React,{useEffect,useRef,useState} from 'react';
import {api,type Ref} from './api';

export type ContextRecord={record_id:string;kind:string;content:string;subject_refs:string[];source_refs:Ref[];conversation_id:string;topic_id:string|null;valid_time:{start:string|null;end:string|null};person_access_events:{person_id:string;learned_at:string|null}[];lifecycle_status:string;reuse_policy:{memory:string};retention_policy:{expires_at:string|null}};
export type Explain={answer_id:string;run_id:string;snapshot_id:string;judgment_basis:{claim?:string;record_id?:string;kind?:string;operation_output_id?:string;text?:string}[];known_information?:ContextRecord[];uncertainties?:string[];source_links:Ref[];redactions:string[];outdated?:boolean;mode:string;development_only?:boolean};
export {ProductDialog as Dialog} from './ProductDialog';
import {ProductDialog as Dialog} from './ProductDialog';
const labels:Record<string,string>={USER_REPORTED_EVENT:'用户报告',USER_GUESS:'用户猜测',CHARACTER_SELF_REPORT:'人物自述',THIRD_PARTY_REPORT:'转述',SYSTEM_INTERPRETATION:'系统解释',CONDITIONAL_RULE:'条件判据',CORRECTION:'更正',RETRACTION:'撤回',HYPOTHETICAL:'假设'};
export function Memory({records,sources,onRevision,onClose}:{records:ContextRecord[];sources:{id:string;name:string;memory:string;stopped:boolean}[];onRevision:(action:string,record:ContextRecord|{record_id:string},data?:unknown)=>Promise<void>;onClose:()=>void}){
 const [edit,setEdit]=useState<{record:ContextRecord;mode:string}|null>(null),[value,setValue]=useState(''),[timeKind,setTimeKind]=useState('event'),[working,setWorking]=useState(false),[error,setError]=useState('');
 async function submit(action:string,record:ContextRecord|{record_id:string},data?:unknown){setWorking(true);setError('');try{await onRevision(action,record,data);setEdit(null);}catch(e){setError(String(e));}finally{setWorking(false);}}
 function correction(){if(!edit)return;const record=edit.record;let data:Record<string,unknown>={kind:record.kind,content:record.content,subject_refs:record.subject_refs,valid_time:record.valid_time,person_access_events:record.person_access_events};
  if(edit.mode==='内容不对')data.content=value;
  if(edit.mode==='人物不对'){const person=(record.topic_id||record.conversation_id)+':'+value;data.subject_refs=[person];data.person_access_events=record.person_access_events.map(e=>({...e,person_id:e.person_id===record.subject_refs[0]?person:e.person_id}));}
  if(edit.mode==='时间不对'){const at=new Date(value).toISOString();if(timeKind==='event')data.valid_time={...record.valid_time,start:at};else data.person_access_events=[{person_id:record.subject_refs[0],learned_at:at}];}
  void submit('CORRECT',record,data);
 }
 return <Dialog label="记忆管理" onClose={onClose}><h2>可管理的背景</h2><p>停止使用会过滤后续回答；删除会清理原文和可恢复派生物。历史回答遵从当前权限。</p>{error&&<p role="alert">{error}</p>}{records.length===0&&<p>当前范围没有已解析背景。</p>}{records.map(record=><section key={record.record_id} className="memory-card"><small>{labels[record.kind]} · {record.lifecycle_status} · {record.reuse_policy.memory}{record.retention_policy.expires_at?' · 有过期时间':''}</small><p>{record.content}</p>{record.lifecycle_status==='ACTIVE'&&<div>{['内容不对','人物不对','时间不对'].map(mode=><button disabled={working} key={mode} onClick={()=>{setEdit({record,mode});setValue(mode==='内容不对'?record.content:'');}}>{mode}</button>)}<button disabled={working} onClick={()=>void submit('CORRECT',record,{kind:'USER_GUESS',content:record.content,subject_refs:record.subject_refs,valid_time:record.valid_time,person_access_events:record.person_access_events})}>这只是猜测</button><button disabled={working} onClick={()=>void submit('RETRACT',record)}>撤回</button><button disabled={working} onClick={()=>void submit('STOP_USING',record)}>停止使用</button></div>}<button disabled={working} onClick={()=>void submit('DELETE',record)}>删除</button></section>)}{sources.filter(s=>s.name!=='message').map(source=><section className="memory-card" key={source.id}><small>注册来源 · {source.memory} · {source.stopped?'STOPPED':'ACTIVE'} · 未声明语义理解</small><p>{source.name}</p>{!source.stopped&&<button disabled={working} onClick={()=>void submit('STOP_USING',{record_id:source.id})}>停止使用文件</button>}<button disabled={working} onClick={()=>void submit('DELETE',{record_id:source.id})}>删除文件</button></section>)}{edit&&<form onSubmit={e=>{e.preventDefault();correction();}}><h3>{edit.mode}</h3>{edit.mode==='时间不对'&&<label>时间含义<select aria-label="时间含义" value={timeKind} onChange={e=>setTimeKind(e.target.value)}><option value="event">事件发生时间</option><option value="learned" disabled={!edit.record.subject_refs.length}>人物获知时间</option></select></label>}<label>{edit.mode==='人物不对'?'正确人物':edit.mode==='时间不对'?'正确时间':'正确内容'}<input autoFocus aria-label="修订值" required type={edit.mode==='时间不对'?'datetime-local':'text'} value={value} onChange={e=>setValue(e.target.value)}/></label><button disabled={working||!value}>提交更正并更新回答</button><button type="button" onClick={()=>setEdit(null)}>取消更正</button></form>}</Dialog>;
}
export function ExplainPanel({value,onClose,onSource,onMemory}:{value:Explain;onClose:()=>void;onSource:(ref:Ref)=>void;onMemory:()=>void}){
 return <Dialog label="查看依据" onClose={onClose}><h2>当次回答依据</h2><p>{value.development_only?'EXPERIMENTAL · 原文有界检查 · 生产禁用':'MOCK · scripted 提取'} · 展开默认零模型调用</p>{value.outdated&&<p>这是旧版本回答的记录。按新信息更新会创建新 run。</p>}{value.redactions.length>0?<p>依据已不可用或按当前权限隐去。</p>:<>{value.judgment_basis.length===0?<p>本次未引用人物背景依据；只记录 Controller 的直接回答。</p>:value.judgment_basis.map(c=><section key={c.record_id??c.operation_output_id}><small>{c.kind?labels[c.kind]:'来源中的显式表达'}</small><p>{c.claim??c.text}</p></section>)}{value.uncertainties?.map((u,i)=><p key={i}>{u}</p>)}{value.source_links.map(ref=><button key={ref.source_id} onClick={()=>onSource(ref)}>查看来源 v{ref.version}</button>)}</>}<button onClick={onMemory}>纠正或管理背景</button><small>回答 / run / snapshot: {value.answer_id} / {value.run_id} / {value.snapshot_id}</small></Dialog>;
}
