import React,{createContext,useLayoutEffect,useRef,useState} from 'react';
type Anchor={element:HTMLElement;selector:string|null;runId:string|null;offset:number;selection:Range|null};
type Controls={capture:(element:HTMLElement)=>void;close:(explicit:boolean,action:()=>void)=>void;selectedRun:string|null;onScroll:()=>void;onIntent:()=>void;panelScroll:(label:string,value?:number)=>number};
export const ReadingAnchorContext=createContext<Controls>({capture:()=>{},close:(_explicit,action)=>action(),selectedRun:null,onScroll:()=>{},onIntent:()=>{},panelScroll:()=>0});
export function useReadingAnchor(scroller:React.RefObject<HTMLDivElement|null>,conversation:string|null,active:boolean):Controls{
 const panelOffsets=useRef(new Map<string,number>());
 const original=useRef<Anchor|null>(null),closing=useRef<Anchor|null>(null),dirty=useRef(false),programmatic=useRef(false),generation=useRef(0),wasActive=useRef(false),lastConversation=useRef(conversation),[selectedRun,setSelectedRun]=useState<string|null>(null);
 function snapshot(element:HTMLElement):Anchor|null{const root=scroller.current;if(!root||!root.contains(element))return null;const id=element.dataset.readingAnchor,run=element.closest<HTMLElement>('[data-run]'),paragraph=element.dataset.readingParagraph;const selector=id?`[data-reading-anchor="${CSS.escape(id)}"]`:run&&paragraph?`[data-run="${CSS.escape(run.dataset.run!)}"] [data-reading-paragraph="${CSS.escape(paragraph)}"]`:run?`[data-run="${CSS.escape(run.dataset.run!)}"]`:null;const selection=window.getSelection();return {element,selector,runId:run?.dataset.run||null,offset:element.getBoundingClientRect().top-root.getBoundingClientRect().top,selection:selection?.rangeCount?selection.getRangeAt(0).cloneRange():null}}
 function visibleAnchor(){const root=scroller.current;if(!root)return null;const top=root.getBoundingClientRect().top;const elements=[...root.querySelectorAll<HTMLElement>('[data-reading-paragraph], [data-reading-anchor], article')];const found=elements.find(el=>{const box=el.getBoundingClientRect();return box.top>=top-1&&box.bottom>top+2})||elements.find(el=>el.getBoundingClientRect().bottom>top);return found?snapshot(found):null}
 function capture(element:HTMLElement){const value=snapshot(element);if(value){generation.current++;panelOffsets.current.clear();original.current=value;closing.current=null;dirty.current=false;setSelectedRun(value.runId)}}
 function close(explicit:boolean,action:()=>void){closing.current=explicit?original.current:dirty.current?visibleAnchor():original.current;action()}
 function restore(value:Anchor|null,focus:boolean){if(!value)return;const token=++generation.current,start=performance.now(),duration=matchMedia('(prefers-reduced-motion: reduce)').matches?40:380;programmatic.current=true;
  const frame=()=>{if(token!==generation.current){programmatic.current=false;return}const root=scroller.current,element=value.selector?root?.querySelector<HTMLElement>(value.selector):value.element;if(!root||!element?.isConnected){programmatic.current=false;return}const delta=element.getBoundingClientRect().top-root.getBoundingClientRect().top-value.offset;if(Math.abs(delta)>.25)root.scrollTop+=delta;if(performance.now()-start<duration){requestAnimationFrame(frame);return}if(focus){if(!element.matches('button,input,textarea,a,[tabindex]'))element.tabIndex=-1;element.focus({preventScroll:true});if(value.selection?.startContainer.isConnected&&value.selection.endContainer.isConnected&&root.contains(value.selection.commonAncestorContainer)){const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(value.selection)}}setTimeout(()=>{if(token===generation.current)programmatic.current=false},0)};requestAnimationFrame(frame)
 }
 useLayoutEffect(()=>{if(lastConversation.current!==conversation){generation.current++;original.current=null;closing.current=null;dirty.current=false;setSelectedRun(null);lastConversation.current=conversation;panelOffsets.current.clear()}if(active&&!wasActive.current)restore(original.current,false);if(!active&&wasActive.current){restore(closing.current??(dirty.current?visibleAnchor():original.current),true);closing.current=null;original.current=null;setSelectedRun(null);panelOffsets.current.clear()}wasActive.current=active},[active,conversation]);
 useLayoutEffect(()=>()=>{generation.current++},[]);
 return {capture,close,selectedRun,onScroll:()=>{if(active&&!programmatic.current)dirty.current=true},onIntent:()=>{if(active)dirty.current=true;generation.current++;programmatic.current=false},panelScroll:(label,value)=>{if(value!==undefined)panelOffsets.current.set(label,value);return panelOffsets.current.get(label)||0}};
}
